/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////


#ifndef __B_U_D_G_E_T_Y_E_A_R__V1_
#define __B_U_D_G_E_T_Y_E_A_R__V1_

////@@begin gen include
#include "wxActiveRecord.h"
#include <wx/wx.h>
#include <wx/string.h>
#include <wx/datetime.h>

////@@end gen include

////@@begin custom include
////@@end custom include

////@@begin gen forward
class BUDGETYEAR_V1;
class BUDGETYEAR_V1Row;
class BUDGETYEAR_V1RowSet;


////@@end gen forward

////@@begin custom forward
////@@end custom forward

////@@begin gen arClass
class BUDGETYEAR_V1: public wxSqliteActiveRecord{
protected:
	BUDGETYEAR_V1Row* RowFromResult(DatabaseResultSet* result);
public:
	BUDGETYEAR_V1();
	BUDGETYEAR_V1(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("BUDGETYEAR_V1"));
	BUDGETYEAR_V1(DatabaseLayer* database,const wxString& table=wxT("BUDGETYEAR_V1"));
	bool Create(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("BUDGETYEAR_V1"));
	
	BUDGETYEAR_V1Row* New();
	bool Delete(int key);

	
	BUDGETYEAR_V1Row* BUDGETYEARID(int key);

	BUDGETYEAR_V1Row* Where(const wxString& whereClause);
	BUDGETYEAR_V1RowSet* WhereSet(const wxString& whereClause,const wxString& orderBy=wxEmptyString);
	BUDGETYEAR_V1RowSet* All(const wxString& orderBy=wxEmptyString); 

////@@begin custom arClass
public:


////@@end custom arClass
};
////@@end gen arClass

////@@begin gen arRow
class BUDGETYEAR_V1Row: public wxActiveRecordRow{
public:
	BUDGETYEAR_V1Row();
	BUDGETYEAR_V1Row(const BUDGETYEAR_V1Row& src);
	BUDGETYEAR_V1Row(BUDGETYEAR_V1* activeRecord);
	BUDGETYEAR_V1Row(DatabaseLayer* database,const wxString& table=wxT("BUDGETYEAR_V1"));
	BUDGETYEAR_V1Row& operator=(const BUDGETYEAR_V1Row& src);
	bool GetFromResult(DatabaseResultSet* result);
public:
	int BUDGETYEARID;
	wxString BUDGETYEARNAME;

public:
	
	
	bool Save();
	bool Delete();
	
	
////@@begin custom arRow
public:


////@@end custom arRow	

};
////@@end gen arRow

////@@begin gen arSet
class BUDGETYEAR_V1RowSet: public wxActiveRecordRowSet{
public:
	BUDGETYEAR_V1RowSet();
	BUDGETYEAR_V1RowSet(wxActiveRecord* activeRecord);
	BUDGETYEAR_V1RowSet(DatabaseLayer* database,const wxString& table=wxT("BUDGETYEAR_V1"));
	virtual BUDGETYEAR_V1Row* Item(unsigned long item);
	
	virtual bool SaveAll();
	
	
protected:
	static int CMPFUNC_BUDGETYEARID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_BUDGETYEARNAME(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_global(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	virtual CMPFUNC_proto GetCmpFunc(const wxString& var) const;

////@@begin custom arSet
public:


////@@end custom arSet
};
////@@end gen arSet

#endif /* __B_U_D_G_E_T_Y_E_A_R__V1_ */