/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////

#include "BUDGETTABLE_V1.h"

/** ACTIVE_RECORD **/
BUDGETTABLE_V1::BUDGETTABLE_V1():wxSqliteActiveRecord(){
}

BUDGETTABLE_V1::BUDGETTABLE_V1(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table):wxSqliteActiveRecord(name,server,user,password,table){
}

BUDGETTABLE_V1::BUDGETTABLE_V1(DatabaseLayer* database,const wxString& table):wxSqliteActiveRecord(database,table){
}

bool BUDGETTABLE_V1::Create(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table){
	return wxSqliteActiveRecord::Create(name,server,user,password,table);
}

BUDGETTABLE_V1Row* BUDGETTABLE_V1::RowFromResult(DatabaseResultSet* result){
	BUDGETTABLE_V1Row* row=new BUDGETTABLE_V1Row(this);
	
	row->GetFromResult(result);
	
	return row;
}

BUDGETTABLE_V1Row* BUDGETTABLE_V1::New(){
	BUDGETTABLE_V1Row* newRow=new BUDGETTABLE_V1Row(this);
	garbageRows.Add(newRow);
	return newRow;
}
bool BUDGETTABLE_V1::Delete(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE BUDGETENTRYID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}



BUDGETTABLE_V1Row* BUDGETTABLE_V1::BUDGETENTRYID(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("SELECT * FROM %s WHERE BUDGETENTRYID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		result->Next();
		BUDGETTABLE_V1Row* row=RowFromResult(result);
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return NULL;
	}
}




BUDGETTABLE_V1Row* BUDGETTABLE_V1::Where(const wxString& whereClause){
	try{
		wxString prepStatement = wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(!result->Next())
			return NULL;
		BUDGETTABLE_V1Row* row=RowFromResult(result);
		
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);						
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

BUDGETTABLE_V1RowSet* BUDGETTABLE_V1::WhereSet(const wxString& whereClause,const wxString& orderBy){
	BUDGETTABLE_V1RowSet* rowSet=new BUDGETTABLE_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}


BUDGETTABLE_V1RowSet* BUDGETTABLE_V1::All(const wxString& orderBy){
	BUDGETTABLE_V1RowSet* rowSet=new BUDGETTABLE_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s"),m_table.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

/** END ACTIVE RECORD **/

/** ACTIVE RECORD ROW **/

BUDGETTABLE_V1Row::BUDGETTABLE_V1Row():wxActiveRecordRow(){
	bool newRow=true;
}

BUDGETTABLE_V1Row::BUDGETTABLE_V1Row(BUDGETTABLE_V1* activeRecord):wxActiveRecordRow(activeRecord){
	bool newRow=true;
}

BUDGETTABLE_V1Row::BUDGETTABLE_V1Row(const BUDGETTABLE_V1Row& src){
	if(&src==this)
		return;
	newRow=src.newRow;
	
	BUDGETENTRYID=src.BUDGETENTRYID;
	SUBCATEGID=src.SUBCATEGID;
	PERIOD=src.PERIOD;
	CATEGID=src.CATEGID;
	AMOUNT=src.AMOUNT;
	BUDGETYEARID=src.BUDGETYEARID;

}

BUDGETTABLE_V1Row::BUDGETTABLE_V1Row(DatabaseLayer* database,const wxString& table):wxActiveRecordRow(database,table){
	newRow=true;
}
	

BUDGETTABLE_V1Row& BUDGETTABLE_V1Row::operator=(const BUDGETTABLE_V1Row& src){
	if(&src==this)
		return *this;
	newRow=src.newRow;
	
	BUDGETENTRYID=src.BUDGETENTRYID;
	SUBCATEGID=src.SUBCATEGID;
	PERIOD=src.PERIOD;
	CATEGID=src.CATEGID;
	AMOUNT=src.AMOUNT;
	BUDGETYEARID=src.BUDGETYEARID;


	return *this;
}

bool BUDGETTABLE_V1Row::GetFromResult(DatabaseResultSet* result){
	
	newRow=false;
		BUDGETENTRYID=result->GetResultInt(wxT("BUDGETENTRYID"));
	SUBCATEGID=result->GetResultInt(wxT("SUBCATEGID"));
	PERIOD=result->GetResultString(wxT("PERIOD"));
	CATEGID=result->GetResultInt(wxT("CATEGID"));
	AMOUNT=result->GetResultInt(wxT("AMOUNT"));
	BUDGETYEARID=result->GetResultInt(wxT("BUDGETYEARID"));


	return true;
}
	

bool BUDGETTABLE_V1Row::Save(){
	try{
		if(newRow){
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("INSERT INTO %s (,SUBCATEGID,PERIOD,CATEGID,AMOUNT,BUDGETYEARID) VALUES (,?,?,?,?,?)"),m_table.c_str()));
			pStatement->SetParamInt(1,SUBCATEGID);
			pStatement->SetParamString(2,PERIOD);
			pStatement->SetParamInt(3,CATEGID);
			pStatement->SetParamInt(4,AMOUNT);
			pStatement->SetParamInt(5,BUDGETYEARID);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

			
			newRow=false;
		}
		else{
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("UPDATE %s SET ,SUBCATEGID=?,PERIOD=?,CATEGID=?,AMOUNT=?,BUDGETYEARID=? WHERE BUDGETENTRYID=?"),m_table.c_str()));
			pStatement->SetParamInt(6,BUDGETENTRYID);
			pStatement->SetParamInt(1,SUBCATEGID);
			pStatement->SetParamString(2,PERIOD);
			pStatement->SetParamInt(3,CATEGID);
			pStatement->SetParamInt(4,AMOUNT);
			pStatement->SetParamInt(5,BUDGETYEARID);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

		}
		
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		wxActiveRecord::ProcessException(e);
		return false;
	}
}

bool BUDGETTABLE_V1Row::Delete(){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE BUDGETENTRYID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,BUDGETENTRYID);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}





/** END ACTIVE RECORD ROW **/

/** ACTIVE RECORD ROW SET **/

BUDGETTABLE_V1RowSet::BUDGETTABLE_V1RowSet():wxActiveRecordRowSet(){
}

BUDGETTABLE_V1RowSet::BUDGETTABLE_V1RowSet(wxActiveRecord* activeRecord):wxActiveRecordRowSet(activeRecord){
}

BUDGETTABLE_V1RowSet::BUDGETTABLE_V1RowSet(DatabaseLayer* database,const wxString& table):wxActiveRecordRowSet(database,table){
}

BUDGETTABLE_V1Row* BUDGETTABLE_V1RowSet::Item(unsigned long item){
	return (BUDGETTABLE_V1Row*)wxActiveRecordRowSet::Item(item);
}


bool BUDGETTABLE_V1RowSet::SaveAll(){
	try{
		m_database->BeginTransaction();
		for(unsigned long i=0;i<Count();i++)
			Item(i)->Save();
		m_database->Commit();
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		m_database->RollBack();
		wxActiveRecord::ProcessException(e);
		return false;
	}
}


int BUDGETTABLE_V1RowSet::CMPFUNC_BUDGETENTRYID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	BUDGETTABLE_V1Row** m_item1=(BUDGETTABLE_V1Row**)item1;
	BUDGETTABLE_V1Row** m_item2=(BUDGETTABLE_V1Row**)item2;
	if((*m_item1)->BUDGETENTRYID<(*m_item2)->BUDGETENTRYID)
		return -1;
	else if((*m_item1)->BUDGETENTRYID>(*m_item2)->BUDGETENTRYID)
		return 1;
	else
		return 0;
}

int BUDGETTABLE_V1RowSet::CMPFUNC_SUBCATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	BUDGETTABLE_V1Row** m_item1=(BUDGETTABLE_V1Row**)item1;
	BUDGETTABLE_V1Row** m_item2=(BUDGETTABLE_V1Row**)item2;
	if((*m_item1)->SUBCATEGID<(*m_item2)->SUBCATEGID)
		return -1;
	else if((*m_item1)->SUBCATEGID>(*m_item2)->SUBCATEGID)
		return 1;
	else
		return 0;
}

int BUDGETTABLE_V1RowSet::CMPFUNC_PERIOD(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	BUDGETTABLE_V1Row** m_item1=(BUDGETTABLE_V1Row**)item1;
	BUDGETTABLE_V1Row** m_item2=(BUDGETTABLE_V1Row**)item2;
	return (*m_item1)->PERIOD.Cmp((*m_item2)->PERIOD);
}

int BUDGETTABLE_V1RowSet::CMPFUNC_CATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	BUDGETTABLE_V1Row** m_item1=(BUDGETTABLE_V1Row**)item1;
	BUDGETTABLE_V1Row** m_item2=(BUDGETTABLE_V1Row**)item2;
	if((*m_item1)->CATEGID<(*m_item2)->CATEGID)
		return -1;
	else if((*m_item1)->CATEGID>(*m_item2)->CATEGID)
		return 1;
	else
		return 0;
}

int BUDGETTABLE_V1RowSet::CMPFUNC_AMOUNT(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	BUDGETTABLE_V1Row** m_item1=(BUDGETTABLE_V1Row**)item1;
	BUDGETTABLE_V1Row** m_item2=(BUDGETTABLE_V1Row**)item2;
	if((*m_item1)->AMOUNT<(*m_item2)->AMOUNT)
		return -1;
	else if((*m_item1)->AMOUNT>(*m_item2)->AMOUNT)
		return 1;
	else
		return 0;
}

int BUDGETTABLE_V1RowSet::CMPFUNC_BUDGETYEARID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	BUDGETTABLE_V1Row** m_item1=(BUDGETTABLE_V1Row**)item1;
	BUDGETTABLE_V1Row** m_item2=(BUDGETTABLE_V1Row**)item2;
	if((*m_item1)->BUDGETYEARID<(*m_item2)->BUDGETYEARID)
		return -1;
	else if((*m_item1)->BUDGETYEARID>(*m_item2)->BUDGETYEARID)
		return 1;
	else
		return 0;
}

CMPFUNC_proto BUDGETTABLE_V1RowSet::GetCmpFunc(const wxString& var) const{
	if(var==wxT("BUDGETENTRYID"))
		return (CMPFUNC_proto)CMPFUNC_BUDGETENTRYID;
	else if(var==wxT("SUBCATEGID"))
		return (CMPFUNC_proto)CMPFUNC_SUBCATEGID;
	else if(var==wxT("PERIOD"))
		return (CMPFUNC_proto)CMPFUNC_PERIOD;
	else if(var==wxT("CATEGID"))
		return (CMPFUNC_proto)CMPFUNC_CATEGID;
	else if(var==wxT("AMOUNT"))
		return (CMPFUNC_proto)CMPFUNC_AMOUNT;
	else if(var==wxT("BUDGETYEARID"))
		return (CMPFUNC_proto)CMPFUNC_BUDGETYEARID;
	else 
	return (CMPFUNC_proto)CMPFUNC_default;
}



/** END ACTIVE RECORD ROW SET **/

////@@begin custom implementations



////@@end custom implementations