/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////


#ifndef __B_U_D_G_E_T_T_A_B_L_E__V1_
#define __B_U_D_G_E_T_T_A_B_L_E__V1_

////@@begin gen include
#include "wxActiveRecord.h"
#include <wx/wx.h>
#include <wx/string.h>
#include <wx/datetime.h>

////@@end gen include

////@@begin custom include
////@@end custom include

////@@begin gen forward
class BUDGETTABLE_V1;
class BUDGETTABLE_V1Row;
class BUDGETTABLE_V1RowSet;


////@@end gen forward

////@@begin custom forward
////@@end custom forward

////@@begin gen arClass
class BUDGETTABLE_V1: public wxSqliteActiveRecord{
protected:
	BUDGETTABLE_V1Row* RowFromResult(DatabaseResultSet* result);
public:
	BUDGETTABLE_V1();
	BUDGETTABLE_V1(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("BUDGETTABLE_V1"));
	BUDGETTABLE_V1(DatabaseLayer* database,const wxString& table=wxT("BUDGETTABLE_V1"));
	bool Create(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("BUDGETTABLE_V1"));
	
	BUDGETTABLE_V1Row* New();
	bool Delete(int key);

	
	BUDGETTABLE_V1Row* BUDGETENTRYID(int key);

	BUDGETTABLE_V1Row* Where(const wxString& whereClause);
	BUDGETTABLE_V1RowSet* WhereSet(const wxString& whereClause,const wxString& orderBy=wxEmptyString);
	BUDGETTABLE_V1RowSet* All(const wxString& orderBy=wxEmptyString); 

////@@begin custom arClass
public:


////@@end custom arClass
};
////@@end gen arClass

////@@begin gen arRow
class BUDGETTABLE_V1Row: public wxActiveRecordRow{
public:
	BUDGETTABLE_V1Row();
	BUDGETTABLE_V1Row(const BUDGETTABLE_V1Row& src);
	BUDGETTABLE_V1Row(BUDGETTABLE_V1* activeRecord);
	BUDGETTABLE_V1Row(DatabaseLayer* database,const wxString& table=wxT("BUDGETTABLE_V1"));
	BUDGETTABLE_V1Row& operator=(const BUDGETTABLE_V1Row& src);
	bool GetFromResult(DatabaseResultSet* result);
public:
	int BUDGETENTRYID;
	int SUBCATEGID;
	wxString PERIOD;
	int CATEGID;
	int AMOUNT;
	int BUDGETYEARID;

public:
	
	
	bool Save();
	bool Delete();
	
	
////@@begin custom arRow
public:


////@@end custom arRow	

};
////@@end gen arRow

////@@begin gen arSet
class BUDGETTABLE_V1RowSet: public wxActiveRecordRowSet{
public:
	BUDGETTABLE_V1RowSet();
	BUDGETTABLE_V1RowSet(wxActiveRecord* activeRecord);
	BUDGETTABLE_V1RowSet(DatabaseLayer* database,const wxString& table=wxT("BUDGETTABLE_V1"));
	virtual BUDGETTABLE_V1Row* Item(unsigned long item);
	
	virtual bool SaveAll();
	
	
protected:
	static int CMPFUNC_BUDGETENTRYID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_SUBCATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_PERIOD(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_CATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_AMOUNT(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_BUDGETYEARID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_global(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	virtual CMPFUNC_proto GetCmpFunc(const wxString& var) const;

////@@begin custom arSet
public:


////@@end custom arSet
};
////@@end gen arSet

#endif /* __B_U_D_G_E_T_T_A_B_L_E__V1_ */