/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////

#include "BUDGETYEAR_V1.h"

/** ACTIVE_RECORD **/
BUDGETYEAR_V1::BUDGETYEAR_V1():wxSqliteActiveRecord(){
}

BUDGETYEAR_V1::BUDGETYEAR_V1(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table):wxSqliteActiveRecord(name,server,user,password,table){
}

BUDGETYEAR_V1::BUDGETYEAR_V1(DatabaseLayer* database,const wxString& table):wxSqliteActiveRecord(database,table){
}

bool BUDGETYEAR_V1::Create(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table){
	return wxSqliteActiveRecord::Create(name,server,user,password,table);
}

BUDGETYEAR_V1Row* BUDGETYEAR_V1::RowFromResult(DatabaseResultSet* result){
	BUDGETYEAR_V1Row* row=new BUDGETYEAR_V1Row(this);
	
	row->GetFromResult(result);
	
	return row;
}

BUDGETYEAR_V1Row* BUDGETYEAR_V1::New(){
	BUDGETYEAR_V1Row* newRow=new BUDGETYEAR_V1Row(this);
	garbageRows.Add(newRow);
	return newRow;
}
bool BUDGETYEAR_V1::Delete(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE BUDGETYEARID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}



BUDGETYEAR_V1Row* BUDGETYEAR_V1::BUDGETYEARID(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("SELECT * FROM %s WHERE BUDGETYEARID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		result->Next();
		BUDGETYEAR_V1Row* row=RowFromResult(result);
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return NULL;
	}
}




BUDGETYEAR_V1Row* BUDGETYEAR_V1::Where(const wxString& whereClause){
	try{
		wxString prepStatement = wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(!result->Next())
			return NULL;
		BUDGETYEAR_V1Row* row=RowFromResult(result);
		
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);						
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

BUDGETYEAR_V1RowSet* BUDGETYEAR_V1::WhereSet(const wxString& whereClause,const wxString& orderBy){
	BUDGETYEAR_V1RowSet* rowSet=new BUDGETYEAR_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}


BUDGETYEAR_V1RowSet* BUDGETYEAR_V1::All(const wxString& orderBy){
	BUDGETYEAR_V1RowSet* rowSet=new BUDGETYEAR_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s"),m_table.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

/** END ACTIVE RECORD **/

/** ACTIVE RECORD ROW **/

BUDGETYEAR_V1Row::BUDGETYEAR_V1Row():wxActiveRecordRow(){
	bool newRow=true;
}

BUDGETYEAR_V1Row::BUDGETYEAR_V1Row(BUDGETYEAR_V1* activeRecord):wxActiveRecordRow(activeRecord){
	bool newRow=true;
}

BUDGETYEAR_V1Row::BUDGETYEAR_V1Row(const BUDGETYEAR_V1Row& src){
	if(&src==this)
		return;
	newRow=src.newRow;
	
	BUDGETYEARID=src.BUDGETYEARID;
	BUDGETYEARNAME=src.BUDGETYEARNAME;

}

BUDGETYEAR_V1Row::BUDGETYEAR_V1Row(DatabaseLayer* database,const wxString& table):wxActiveRecordRow(database,table){
	newRow=true;
}
	

BUDGETYEAR_V1Row& BUDGETYEAR_V1Row::operator=(const BUDGETYEAR_V1Row& src){
	if(&src==this)
		return *this;
	newRow=src.newRow;
	
	BUDGETYEARID=src.BUDGETYEARID;
	BUDGETYEARNAME=src.BUDGETYEARNAME;


	return *this;
}

bool BUDGETYEAR_V1Row::GetFromResult(DatabaseResultSet* result){
	
	newRow=false;
		BUDGETYEARID=result->GetResultInt(wxT("BUDGETYEARID"));
	BUDGETYEARNAME=result->GetResultString(wxT("BUDGETYEARNAME"));


	return true;
}
	

bool BUDGETYEAR_V1Row::Save(){
	try{
		if(newRow){
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("INSERT INTO %s (,BUDGETYEARNAME) VALUES (,?)"),m_table.c_str()));
			pStatement->SetParamString(1,BUDGETYEARNAME);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

			
			newRow=false;
		}
		else{
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("UPDATE %s SET ,BUDGETYEARNAME=? WHERE BUDGETYEARID=?"),m_table.c_str()));
			pStatement->SetParamInt(2,BUDGETYEARID);
			pStatement->SetParamString(1,BUDGETYEARNAME);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

		}
		
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		wxActiveRecord::ProcessException(e);
		return false;
	}
}

bool BUDGETYEAR_V1Row::Delete(){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE BUDGETYEARID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,BUDGETYEARID);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}





/** END ACTIVE RECORD ROW **/

/** ACTIVE RECORD ROW SET **/

BUDGETYEAR_V1RowSet::BUDGETYEAR_V1RowSet():wxActiveRecordRowSet(){
}

BUDGETYEAR_V1RowSet::BUDGETYEAR_V1RowSet(wxActiveRecord* activeRecord):wxActiveRecordRowSet(activeRecord){
}

BUDGETYEAR_V1RowSet::BUDGETYEAR_V1RowSet(DatabaseLayer* database,const wxString& table):wxActiveRecordRowSet(database,table){
}

BUDGETYEAR_V1Row* BUDGETYEAR_V1RowSet::Item(unsigned long item){
	return (BUDGETYEAR_V1Row*)wxActiveRecordRowSet::Item(item);
}


bool BUDGETYEAR_V1RowSet::SaveAll(){
	try{
		m_database->BeginTransaction();
		for(unsigned long i=0;i<Count();i++)
			Item(i)->Save();
		m_database->Commit();
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		m_database->RollBack();
		wxActiveRecord::ProcessException(e);
		return false;
	}
}


int BUDGETYEAR_V1RowSet::CMPFUNC_BUDGETYEARID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	BUDGETYEAR_V1Row** m_item1=(BUDGETYEAR_V1Row**)item1;
	BUDGETYEAR_V1Row** m_item2=(BUDGETYEAR_V1Row**)item2;
	if((*m_item1)->BUDGETYEARID<(*m_item2)->BUDGETYEARID)
		return -1;
	else if((*m_item1)->BUDGETYEARID>(*m_item2)->BUDGETYEARID)
		return 1;
	else
		return 0;
}

int BUDGETYEAR_V1RowSet::CMPFUNC_BUDGETYEARNAME(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	BUDGETYEAR_V1Row** m_item1=(BUDGETYEAR_V1Row**)item1;
	BUDGETYEAR_V1Row** m_item2=(BUDGETYEAR_V1Row**)item2;
	return (*m_item1)->BUDGETYEARNAME.Cmp((*m_item2)->BUDGETYEARNAME);
}

CMPFUNC_proto BUDGETYEAR_V1RowSet::GetCmpFunc(const wxString& var) const{
	if(var==wxT("BUDGETYEARID"))
		return (CMPFUNC_proto)CMPFUNC_BUDGETYEARID;
	else if(var==wxT("BUDGETYEARNAME"))
		return (CMPFUNC_proto)CMPFUNC_BUDGETYEARNAME;
	else 
	return (CMPFUNC_proto)CMPFUNC_default;
}



/** END ACTIVE RECORD ROW SET **/

////@@begin custom implementations



////@@end custom implementations