/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////


#ifndef __B_U_D_G_E_T_S_P_L_I_T_T_R_A_N_S_A_C_T_I_O_N_S__V1_
#define __B_U_D_G_E_T_S_P_L_I_T_T_R_A_N_S_A_C_T_I_O_N_S__V1_

////@@begin gen include
#include "wxActiveRecord.h"
#include <wx/wx.h>
#include <wx/string.h>
#include <wx/datetime.h>
#include "CHECKINGACCOUNT_V1.h"
#include "CATEGORY_V1.h"
#include "SUBCATEGORY_V1.h"

////@@end gen include

////@@begin custom include
////@@end custom include

////@@begin gen forward
class BUDGETSPLITTRANSACTIONS_V1;
class BUDGETSPLITTRANSACTIONS_V1Row;
class BUDGETSPLITTRANSACTIONS_V1RowSet;

class CHECKINGACCOUNT_V1;
class CHECKINGACCOUNT_V1Row;
class CHECKINGACCOUNT_V1RowSet;
class CATEGORY_V1;
class CATEGORY_V1Row;
class CATEGORY_V1RowSet;
class SUBCATEGORY_V1;
class SUBCATEGORY_V1Row;
class SUBCATEGORY_V1RowSet;

////@@end gen forward

////@@begin custom forward
////@@end custom forward

////@@begin gen arClass
class BUDGETSPLITTRANSACTIONS_V1: public wxSqliteActiveRecord{
protected:
	BUDGETSPLITTRANSACTIONS_V1Row* RowFromResult(DatabaseResultSet* result);
public:
	BUDGETSPLITTRANSACTIONS_V1();
	BUDGETSPLITTRANSACTIONS_V1(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("BUDGETSPLITTRANSACTIONS_V1"));
	BUDGETSPLITTRANSACTIONS_V1(DatabaseLayer* database,const wxString& table=wxT("BUDGETSPLITTRANSACTIONS_V1"));
	bool Create(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("BUDGETSPLITTRANSACTIONS_V1"));
	
	BUDGETSPLITTRANSACTIONS_V1Row* New();
	bool Delete(int key);

	
	BUDGETSPLITTRANSACTIONS_V1Row* SPLITTRANSID(int key);

	BUDGETSPLITTRANSACTIONS_V1Row* Where(const wxString& whereClause);
	BUDGETSPLITTRANSACTIONS_V1RowSet* WhereSet(const wxString& whereClause,const wxString& orderBy=wxEmptyString);
	BUDGETSPLITTRANSACTIONS_V1RowSet* All(const wxString& orderBy=wxEmptyString); 

////@@begin custom arClass
public:


////@@end custom arClass
};
////@@end gen arClass

////@@begin gen arRow
class BUDGETSPLITTRANSACTIONS_V1Row: public wxActiveRecordRow{
public:
	BUDGETSPLITTRANSACTIONS_V1Row();
	BUDGETSPLITTRANSACTIONS_V1Row(const BUDGETSPLITTRANSACTIONS_V1Row& src);
	BUDGETSPLITTRANSACTIONS_V1Row(BUDGETSPLITTRANSACTIONS_V1* activeRecord);
	BUDGETSPLITTRANSACTIONS_V1Row(DatabaseLayer* database,const wxString& table=wxT("BUDGETSPLITTRANSACTIONS_V1"));
	BUDGETSPLITTRANSACTIONS_V1Row& operator=(const BUDGETSPLITTRANSACTIONS_V1Row& src);
	bool GetFromResult(DatabaseResultSet* result);
public:
	int SUBCATEGID;
	wxString SPLITTRANSAMOUNT;
	int SPLITTRANSID;
	int CATEGID;
	int TRANSID;

public:
	CHECKINGACCOUNT_V1Row* GetCHECKINGACCOUNT_V1();
	CATEGORY_V1Row* GetCATEGORY_V1();
	SUBCATEGORY_V1Row* GetSUBCATEGORY_V1();

	
	bool Save();
	bool Delete();
	
	
////@@begin custom arRow
public:


////@@end custom arRow	

};
////@@end gen arRow

////@@begin gen arSet
class BUDGETSPLITTRANSACTIONS_V1RowSet: public wxActiveRecordRowSet{
public:
	BUDGETSPLITTRANSACTIONS_V1RowSet();
	BUDGETSPLITTRANSACTIONS_V1RowSet(wxActiveRecord* activeRecord);
	BUDGETSPLITTRANSACTIONS_V1RowSet(DatabaseLayer* database,const wxString& table=wxT("BUDGETSPLITTRANSACTIONS_V1"));
	virtual BUDGETSPLITTRANSACTIONS_V1Row* Item(unsigned long item);
	
	virtual bool SaveAll();
	
	
protected:
	static int CMPFUNC_SUBCATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_SPLITTRANSAMOUNT(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_SPLITTRANSID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_CATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_TRANSID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_global(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	virtual CMPFUNC_proto GetCmpFunc(const wxString& var) const;

////@@begin custom arSet
public:


////@@end custom arSet
};
////@@end gen arSet

#endif /* __B_U_D_G_E_T_S_P_L_I_T_T_R_A_N_S_A_C_T_I_O_N_S__V1_ */