/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////

#include "CATEGORY_V1.h"

/** ACTIVE_RECORD **/
CATEGORY_V1::CATEGORY_V1():wxSqliteActiveRecord(){
}

CATEGORY_V1::CATEGORY_V1(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table):wxSqliteActiveRecord(name,server,user,password,table){
}

CATEGORY_V1::CATEGORY_V1(DatabaseLayer* database,const wxString& table):wxSqliteActiveRecord(database,table){
}

bool CATEGORY_V1::Create(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table){
	return wxSqliteActiveRecord::Create(name,server,user,password,table);
}

CATEGORY_V1Row* CATEGORY_V1::RowFromResult(DatabaseResultSet* result){
	CATEGORY_V1Row* row=new CATEGORY_V1Row(this);
	
	row->GetFromResult(result);
	
	return row;
}

CATEGORY_V1Row* CATEGORY_V1::New(){
	CATEGORY_V1Row* newRow=new CATEGORY_V1Row(this);
	garbageRows.Add(newRow);
	return newRow;
}
bool CATEGORY_V1::Delete(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE CATEGID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}



CATEGORY_V1Row* CATEGORY_V1::CATEGID(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("SELECT * FROM %s WHERE CATEGID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		result->Next();
		CATEGORY_V1Row* row=RowFromResult(result);
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return NULL;
	}
}




CATEGORY_V1Row* CATEGORY_V1::Where(const wxString& whereClause){
	try{
		wxString prepStatement = wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(!result->Next())
			return NULL;
		CATEGORY_V1Row* row=RowFromResult(result);
		
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);						
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

CATEGORY_V1RowSet* CATEGORY_V1::WhereSet(const wxString& whereClause,const wxString& orderBy){
	CATEGORY_V1RowSet* rowSet=new CATEGORY_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}


CATEGORY_V1RowSet* CATEGORY_V1::All(const wxString& orderBy){
	CATEGORY_V1RowSet* rowSet=new CATEGORY_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s"),m_table.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

/** END ACTIVE RECORD **/

/** ACTIVE RECORD ROW **/

CATEGORY_V1Row::CATEGORY_V1Row():wxActiveRecordRow(){
	bool newRow=true;
}

CATEGORY_V1Row::CATEGORY_V1Row(CATEGORY_V1* activeRecord):wxActiveRecordRow(activeRecord){
	bool newRow=true;
}

CATEGORY_V1Row::CATEGORY_V1Row(const CATEGORY_V1Row& src){
	if(&src==this)
		return;
	newRow=src.newRow;
	
	CATEGID=src.CATEGID;
	CATEGNAME=src.CATEGNAME;

}

CATEGORY_V1Row::CATEGORY_V1Row(DatabaseLayer* database,const wxString& table):wxActiveRecordRow(database,table){
	newRow=true;
}
	

CATEGORY_V1Row& CATEGORY_V1Row::operator=(const CATEGORY_V1Row& src){
	if(&src==this)
		return *this;
	newRow=src.newRow;
	
	CATEGID=src.CATEGID;
	CATEGNAME=src.CATEGNAME;


	return *this;
}

bool CATEGORY_V1Row::GetFromResult(DatabaseResultSet* result){
	
	newRow=false;
		CATEGID=result->GetResultInt(wxT("CATEGID"));
	CATEGNAME=result->GetResultString(wxT("CATEGNAME"));


	return true;
}
	

bool CATEGORY_V1Row::Save(){
	try{
		if(newRow){
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("INSERT INTO %s (,CATEGNAME) VALUES (,?)"),m_table.c_str()));
			pStatement->SetParamString(1,CATEGNAME);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

			
			newRow=false;
		}
		else{
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("UPDATE %s SET ,CATEGNAME=? WHERE CATEGID=?"),m_table.c_str()));
			pStatement->SetParamInt(2,CATEGID);
			pStatement->SetParamString(1,CATEGNAME);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

		}
		
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		wxActiveRecord::ProcessException(e);
		return false;
	}
}

bool CATEGORY_V1Row::Delete(){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE CATEGID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,CATEGID);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}



SUBCATEGORY_V1RowSet* CATEGORY_V1Row::GetSUBCATEGORY_V1s(const wxString& orderBy){
	SUBCATEGORY_V1RowSet* set= new SUBCATEGORY_V1RowSet(m_database,wxT("SUBCATEGORY_V1"));
	wxString str_statement =wxT("SELECT * FROM SUBCATEGORY_V1 WHERE CATEGID=?");
	if(!orderBy.IsEmpty())
		str_statement+=wxT(" ORDER BY ")+orderBy;
	PreparedStatement* pStatement=m_database->PrepareStatement(str_statement);
	pStatement->SetParamInt(1,CATEGID);
	DatabaseResultSet* result= pStatement->ExecuteQuery();

	while(result->Next()){
		SUBCATEGORY_V1Row* toAdd=new SUBCATEGORY_V1Row(m_database,wxT("SUBCATEGORY_V1"));
		toAdd->GetFromResult(result);
		set->Add(toAdd);
	}
	garbageRowSets.Add(set);
	m_database->CloseResultSet(result);
	m_database->CloseStatement(pStatement);
	return set;
}



/** END ACTIVE RECORD ROW **/

/** ACTIVE RECORD ROW SET **/

CATEGORY_V1RowSet::CATEGORY_V1RowSet():wxActiveRecordRowSet(){
}

CATEGORY_V1RowSet::CATEGORY_V1RowSet(wxActiveRecord* activeRecord):wxActiveRecordRowSet(activeRecord){
}

CATEGORY_V1RowSet::CATEGORY_V1RowSet(DatabaseLayer* database,const wxString& table):wxActiveRecordRowSet(database,table){
}

CATEGORY_V1Row* CATEGORY_V1RowSet::Item(unsigned long item){
	return (CATEGORY_V1Row*)wxActiveRecordRowSet::Item(item);
}


bool CATEGORY_V1RowSet::SaveAll(){
	try{
		m_database->BeginTransaction();
		for(unsigned long i=0;i<Count();i++)
			Item(i)->Save();
		m_database->Commit();
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		m_database->RollBack();
		wxActiveRecord::ProcessException(e);
		return false;
	}
}


int CATEGORY_V1RowSet::CMPFUNC_CATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CATEGORY_V1Row** m_item1=(CATEGORY_V1Row**)item1;
	CATEGORY_V1Row** m_item2=(CATEGORY_V1Row**)item2;
	if((*m_item1)->CATEGID<(*m_item2)->CATEGID)
		return -1;
	else if((*m_item1)->CATEGID>(*m_item2)->CATEGID)
		return 1;
	else
		return 0;
}

int CATEGORY_V1RowSet::CMPFUNC_CATEGNAME(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CATEGORY_V1Row** m_item1=(CATEGORY_V1Row**)item1;
	CATEGORY_V1Row** m_item2=(CATEGORY_V1Row**)item2;
	return (*m_item1)->CATEGNAME.Cmp((*m_item2)->CATEGNAME);
}

CMPFUNC_proto CATEGORY_V1RowSet::GetCmpFunc(const wxString& var) const{
	if(var==wxT("CATEGID"))
		return (CMPFUNC_proto)CMPFUNC_CATEGID;
	else if(var==wxT("CATEGNAME"))
		return (CMPFUNC_proto)CMPFUNC_CATEGNAME;
	else 
	return (CMPFUNC_proto)CMPFUNC_default;
}



/** END ACTIVE RECORD ROW SET **/

////@@begin custom implementations



////@@end custom implementations