/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////


#ifndef __C_A_T_E_G_O_R_Y__V1_
#define __C_A_T_E_G_O_R_Y__V1_

////@@begin gen include
#include "wxActiveRecord.h"
#include <wx/wx.h>
#include <wx/string.h>
#include <wx/datetime.h>
#include "SUBCATEGORY_V1.h"

////@@end gen include

////@@begin custom include
////@@end custom include

////@@begin gen forward
class CATEGORY_V1;
class CATEGORY_V1Row;
class CATEGORY_V1RowSet;

class SUBCATEGORY_V1;
class SUBCATEGORY_V1Row;
class SUBCATEGORY_V1RowSet;

////@@end gen forward

////@@begin custom forward
////@@end custom forward

////@@begin gen arClass
class CATEGORY_V1: public wxSqliteActiveRecord{
protected:
	CATEGORY_V1Row* RowFromResult(DatabaseResultSet* result);
public:
	CATEGORY_V1();
	CATEGORY_V1(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("CATEGORY_V1"));
	CATEGORY_V1(DatabaseLayer* database,const wxString& table=wxT("CATEGORY_V1"));
	bool Create(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("CATEGORY_V1"));
	
	CATEGORY_V1Row* New();
	bool Delete(int key);

	
	CATEGORY_V1Row* CATEGID(int key);

	CATEGORY_V1Row* Where(const wxString& whereClause);
	CATEGORY_V1RowSet* WhereSet(const wxString& whereClause,const wxString& orderBy=wxEmptyString);
	CATEGORY_V1RowSet* All(const wxString& orderBy=wxEmptyString); 

////@@begin custom arClass
public:


////@@end custom arClass
};
////@@end gen arClass

////@@begin gen arRow
class CATEGORY_V1Row: public wxActiveRecordRow{
public:
	CATEGORY_V1Row();
	CATEGORY_V1Row(const CATEGORY_V1Row& src);
	CATEGORY_V1Row(CATEGORY_V1* activeRecord);
	CATEGORY_V1Row(DatabaseLayer* database,const wxString& table=wxT("CATEGORY_V1"));
	CATEGORY_V1Row& operator=(const CATEGORY_V1Row& src);
	bool GetFromResult(DatabaseResultSet* result);
public:
	int CATEGID;
	wxString CATEGNAME;

public:
	SUBCATEGORY_V1RowSet* GetSUBCATEGORY_V1s(const wxString& orderBy=wxEmptyString);

	
	bool Save();
	bool Delete();
	
	
////@@begin custom arRow
public:


////@@end custom arRow	

};
////@@end gen arRow

////@@begin gen arSet
class CATEGORY_V1RowSet: public wxActiveRecordRowSet{
public:
	CATEGORY_V1RowSet();
	CATEGORY_V1RowSet(wxActiveRecord* activeRecord);
	CATEGORY_V1RowSet(DatabaseLayer* database,const wxString& table=wxT("CATEGORY_V1"));
	virtual CATEGORY_V1Row* Item(unsigned long item);
	
	virtual bool SaveAll();
	
	
protected:
	static int CMPFUNC_CATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_CATEGNAME(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_global(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	virtual CMPFUNC_proto GetCmpFunc(const wxString& var) const;

////@@begin custom arSet
public:


////@@end custom arSet
};
////@@end gen arSet

#endif /* __C_A_T_E_G_O_R_Y__V1_ */