/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////

#include "CHECKINGACCOUNT_V1.h"

/** ACTIVE_RECORD **/
CHECKINGACCOUNT_V1::CHECKINGACCOUNT_V1():wxSqliteActiveRecord(){
}

CHECKINGACCOUNT_V1::CHECKINGACCOUNT_V1(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table):wxSqliteActiveRecord(name,server,user,password,table){
}

CHECKINGACCOUNT_V1::CHECKINGACCOUNT_V1(DatabaseLayer* database,const wxString& table):wxSqliteActiveRecord(database,table){
}

bool CHECKINGACCOUNT_V1::Create(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table){
	return wxSqliteActiveRecord::Create(name,server,user,password,table);
}

CHECKINGACCOUNT_V1Row* CHECKINGACCOUNT_V1::RowFromResult(DatabaseResultSet* result){
	CHECKINGACCOUNT_V1Row* row=new CHECKINGACCOUNT_V1Row(this);
	
	row->GetFromResult(result);
	
	return row;
}

CHECKINGACCOUNT_V1Row* CHECKINGACCOUNT_V1::New(){
	CHECKINGACCOUNT_V1Row* newRow=new CHECKINGACCOUNT_V1Row(this);
	garbageRows.Add(newRow);
	return newRow;
}
bool CHECKINGACCOUNT_V1::Delete(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE TRANSID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}



CHECKINGACCOUNT_V1Row* CHECKINGACCOUNT_V1::TRANSID(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("SELECT * FROM %s WHERE TRANSID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		result->Next();
		CHECKINGACCOUNT_V1Row* row=RowFromResult(result);
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return NULL;
	}
}




CHECKINGACCOUNT_V1Row* CHECKINGACCOUNT_V1::Where(const wxString& whereClause){
	try{
		wxString prepStatement = wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(!result->Next())
			return NULL;
		CHECKINGACCOUNT_V1Row* row=RowFromResult(result);
		
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);						
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

CHECKINGACCOUNT_V1RowSet* CHECKINGACCOUNT_V1::WhereSet(const wxString& whereClause,const wxString& orderBy){
	CHECKINGACCOUNT_V1RowSet* rowSet=new CHECKINGACCOUNT_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}


CHECKINGACCOUNT_V1RowSet* CHECKINGACCOUNT_V1::All(const wxString& orderBy){
	CHECKINGACCOUNT_V1RowSet* rowSet=new CHECKINGACCOUNT_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s"),m_table.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

/** END ACTIVE RECORD **/

/** ACTIVE RECORD ROW **/

CHECKINGACCOUNT_V1Row::CHECKINGACCOUNT_V1Row():wxActiveRecordRow(){
	bool newRow=true;
}

CHECKINGACCOUNT_V1Row::CHECKINGACCOUNT_V1Row(CHECKINGACCOUNT_V1* activeRecord):wxActiveRecordRow(activeRecord){
	bool newRow=true;
}

CHECKINGACCOUNT_V1Row::CHECKINGACCOUNT_V1Row(const CHECKINGACCOUNT_V1Row& src){
	if(&src==this)
		return;
	newRow=src.newRow;
	
	TRANSAMOUNT=src.TRANSAMOUNT;
	TRANSCODE=src.TRANSCODE;
	SUBCATEGID=src.SUBCATEGID;
	PAYEEID=src.PAYEEID;
	TOACCOUNTID=src.TOACCOUNTID;
	CATEGID=src.CATEGID;
	NOTES=src.NOTES;
	STATUS=src.STATUS;
	TRANSACTIONNUMBER=src.TRANSACTIONNUMBER;
	TOTRANSAMOUNT=src.TOTRANSAMOUNT;
	ACCOUNTID=src.ACCOUNTID;
	FOLLOWUPID=src.FOLLOWUPID;
	TRANSDATE=src.TRANSDATE;
	TRANSID=src.TRANSID;

}

CHECKINGACCOUNT_V1Row::CHECKINGACCOUNT_V1Row(DatabaseLayer* database,const wxString& table):wxActiveRecordRow(database,table){
	newRow=true;
}
	

CHECKINGACCOUNT_V1Row& CHECKINGACCOUNT_V1Row::operator=(const CHECKINGACCOUNT_V1Row& src){
	if(&src==this)
		return *this;
	newRow=src.newRow;
	
	TRANSAMOUNT=src.TRANSAMOUNT;
	TRANSCODE=src.TRANSCODE;
	SUBCATEGID=src.SUBCATEGID;
	PAYEEID=src.PAYEEID;
	TOACCOUNTID=src.TOACCOUNTID;
	CATEGID=src.CATEGID;
	NOTES=src.NOTES;
	STATUS=src.STATUS;
	TRANSACTIONNUMBER=src.TRANSACTIONNUMBER;
	TOTRANSAMOUNT=src.TOTRANSAMOUNT;
	ACCOUNTID=src.ACCOUNTID;
	FOLLOWUPID=src.FOLLOWUPID;
	TRANSDATE=src.TRANSDATE;
	TRANSID=src.TRANSID;


	return *this;
}

bool CHECKINGACCOUNT_V1Row::GetFromResult(DatabaseResultSet* result){
	
	newRow=false;
		TRANSAMOUNT=result->GetResultInt(wxT("TRANSAMOUNT"));
	TRANSCODE=result->GetResultString(wxT("TRANSCODE"));
	SUBCATEGID=result->GetResultInt(wxT("SUBCATEGID"));
	PAYEEID=result->GetResultInt(wxT("PAYEEID"));
	TOACCOUNTID=result->GetResultInt(wxT("TOACCOUNTID"));
	CATEGID=result->GetResultInt(wxT("CATEGID"));
	NOTES=result->GetResultString(wxT("NOTES"));
	STATUS=result->GetResultString(wxT("STATUS"));
	TRANSACTIONNUMBER=result->GetResultString(wxT("TRANSACTIONNUMBER"));
	TOTRANSAMOUNT=result->GetResultInt(wxT("TOTRANSAMOUNT"));
	ACCOUNTID=result->GetResultInt(wxT("ACCOUNTID"));
	FOLLOWUPID=result->GetResultInt(wxT("FOLLOWUPID"));
	TRANSDATE=result->GetResultString(wxT("TRANSDATE"));
	TRANSID=result->GetResultInt(wxT("TRANSID"));


	return true;
}
	

bool CHECKINGACCOUNT_V1Row::Save(){
	try{
		if(newRow){
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("INSERT INTO %s (TRANSAMOUNT,TRANSCODE,SUBCATEGID,PAYEEID,TOACCOUNTID,CATEGID,NOTES,STATUS,TRANSACTIONNUMBER,TOTRANSAMOUNT,ACCOUNTID,FOLLOWUPID,TRANSDATE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)"),m_table.c_str()));
			pStatement->SetParamInt(1,TRANSAMOUNT);
			pStatement->SetParamString(2,TRANSCODE);
			pStatement->SetParamInt(3,SUBCATEGID);
			pStatement->SetParamInt(4,PAYEEID);
			pStatement->SetParamInt(5,TOACCOUNTID);
			pStatement->SetParamInt(6,CATEGID);
			pStatement->SetParamString(7,NOTES);
			pStatement->SetParamString(8,STATUS);
			pStatement->SetParamString(9,TRANSACTIONNUMBER);
			pStatement->SetParamInt(10,TOTRANSAMOUNT);
			pStatement->SetParamInt(11,ACCOUNTID);
			pStatement->SetParamInt(12,FOLLOWUPID);
			pStatement->SetParamString(13,TRANSDATE);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

			
			newRow=false;
		}
		else{
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("UPDATE %s SET TRANSAMOUNT=?,TRANSCODE=?,SUBCATEGID=?,PAYEEID=?,TOACCOUNTID=?,CATEGID=?,NOTES=?,STATUS=?,TRANSACTIONNUMBER=?,TOTRANSAMOUNT=?,ACCOUNTID=?,FOLLOWUPID=?,TRANSDATE=? WHERE TRANSID=?"),m_table.c_str()));
			pStatement->SetParamInt(1,TRANSAMOUNT);
			pStatement->SetParamString(2,TRANSCODE);
			pStatement->SetParamInt(3,SUBCATEGID);
			pStatement->SetParamInt(4,PAYEEID);
			pStatement->SetParamInt(5,TOACCOUNTID);
			pStatement->SetParamInt(6,CATEGID);
			pStatement->SetParamString(7,NOTES);
			pStatement->SetParamString(8,STATUS);
			pStatement->SetParamString(9,TRANSACTIONNUMBER);
			pStatement->SetParamInt(10,TOTRANSAMOUNT);
			pStatement->SetParamInt(11,ACCOUNTID);
			pStatement->SetParamInt(12,FOLLOWUPID);
			pStatement->SetParamString(13,TRANSDATE);
			pStatement->SetParamInt(14,TRANSID);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

		}
		
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		wxActiveRecord::ProcessException(e);
		return false;
	}
}

bool CHECKINGACCOUNT_V1Row::Delete(){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE TRANSID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,TRANSID);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}



ACCOUNTLIST_V1Row* CHECKINGACCOUNT_V1Row::GetACCOUNTLIST_V1(){
	ACCOUNTLIST_V1Row* owner= new ACCOUNTLIST_V1Row(m_database,wxT("ACCOUNTLIST_V1"));
	PreparedStatement* pStatement=m_database->PrepareStatement(wxT("SELECT * FROM ACCOUNTLIST_V1 WHERE ACCOUNTID=?"));
	pStatement->SetParamInt(1,ACCOUNTID);
	pStatement->SetParamInt(1,ACCOUNTID);
	DatabaseResultSet* result= pStatement->ExecuteQuery();

	result->Next();
	owner->GetFromResult(result);
	garbageRows.Add(owner);
	m_database->CloseResultSet(result);
	m_database->CloseStatement(pStatement);
	return owner;
}

ACCOUNTLIST_V1Row* CHECKINGACCOUNT_V1Row::GetACCOUNTLIST_V1(){
	ACCOUNTLIST_V1Row* owner= new ACCOUNTLIST_V1Row(m_database,wxT("ACCOUNTLIST_V1"));
	PreparedStatement* pStatement=m_database->PrepareStatement(wxT("SELECT * FROM ACCOUNTLIST_V1 WHERE ACCOUNTID=?"));
	pStatement->SetParamInt(1,TOACCOUNTID);
	pStatement->SetParamInt(1,TOACCOUNTID);
	DatabaseResultSet* result= pStatement->ExecuteQuery();

	result->Next();
	owner->GetFromResult(result);
	garbageRows.Add(owner);
	m_database->CloseResultSet(result);
	m_database->CloseStatement(pStatement);
	return owner;
}

PAYEE_V1Row* CHECKINGACCOUNT_V1Row::GetPAYEE_V1(){
	PAYEE_V1Row* owner= new PAYEE_V1Row(m_database,wxT("PAYEE_V1"));
	PreparedStatement* pStatement=m_database->PrepareStatement(wxT("SELECT * FROM PAYEE_V1 WHERE PAYEEID=?"));
	pStatement->SetParamInt(1,PAYEEID);
	pStatement->SetParamInt(1,PAYEEID);
	DatabaseResultSet* result= pStatement->ExecuteQuery();

	result->Next();
	owner->GetFromResult(result);
	garbageRows.Add(owner);
	m_database->CloseResultSet(result);
	m_database->CloseStatement(pStatement);
	return owner;
}

SPLITTRANSACTIONS_V1RowSet* CHECKINGACCOUNT_V1Row::GetSPLITTRANSACTIONS_V1s(const wxString& orderBy){
	SPLITTRANSACTIONS_V1RowSet* set= new SPLITTRANSACTIONS_V1RowSet(m_database,wxT("SPLITTRANSACTIONS_V1"));
	wxString str_statement =wxT("SELECT * FROM SPLITTRANSACTIONS_V1 WHERE TRANSID=?");
	if(!orderBy.IsEmpty())
		str_statement+=wxT(" ORDER BY ")+orderBy;
	PreparedStatement* pStatement=m_database->PrepareStatement(str_statement);
	pStatement->SetParamInt(1,TRANSID);
	DatabaseResultSet* result= pStatement->ExecuteQuery();

	while(result->Next()){
		SPLITTRANSACTIONS_V1Row* toAdd=new SPLITTRANSACTIONS_V1Row(m_database,wxT("SPLITTRANSACTIONS_V1"));
		toAdd->GetFromResult(result);
		set->Add(toAdd);
	}
	garbageRowSets.Add(set);
	m_database->CloseResultSet(result);
	m_database->CloseStatement(pStatement);
	return set;
}



/** END ACTIVE RECORD ROW **/

/** ACTIVE RECORD ROW SET **/

CHECKINGACCOUNT_V1RowSet::CHECKINGACCOUNT_V1RowSet():wxActiveRecordRowSet(){
}

CHECKINGACCOUNT_V1RowSet::CHECKINGACCOUNT_V1RowSet(wxActiveRecord* activeRecord):wxActiveRecordRowSet(activeRecord){
}

CHECKINGACCOUNT_V1RowSet::CHECKINGACCOUNT_V1RowSet(DatabaseLayer* database,const wxString& table):wxActiveRecordRowSet(database,table){
}

CHECKINGACCOUNT_V1Row* CHECKINGACCOUNT_V1RowSet::Item(unsigned long item){
	return (CHECKINGACCOUNT_V1Row*)wxActiveRecordRowSet::Item(item);
}


bool CHECKINGACCOUNT_V1RowSet::SaveAll(){
	try{
		m_database->BeginTransaction();
		for(unsigned long i=0;i<Count();i++)
			Item(i)->Save();
		m_database->Commit();
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		m_database->RollBack();
		wxActiveRecord::ProcessException(e);
		return false;
	}
}


int CHECKINGACCOUNT_V1RowSet::CMPFUNC_TRANSAMOUNT(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	if((*m_item1)->TRANSAMOUNT<(*m_item2)->TRANSAMOUNT)
		return -1;
	else if((*m_item1)->TRANSAMOUNT>(*m_item2)->TRANSAMOUNT)
		return 1;
	else
		return 0;
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_TRANSCODE(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	return (*m_item1)->TRANSCODE.Cmp((*m_item2)->TRANSCODE);
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_SUBCATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	if((*m_item1)->SUBCATEGID<(*m_item2)->SUBCATEGID)
		return -1;
	else if((*m_item1)->SUBCATEGID>(*m_item2)->SUBCATEGID)
		return 1;
	else
		return 0;
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_PAYEEID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	if((*m_item1)->PAYEEID<(*m_item2)->PAYEEID)
		return -1;
	else if((*m_item1)->PAYEEID>(*m_item2)->PAYEEID)
		return 1;
	else
		return 0;
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_TOACCOUNTID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	if((*m_item1)->TOACCOUNTID<(*m_item2)->TOACCOUNTID)
		return -1;
	else if((*m_item1)->TOACCOUNTID>(*m_item2)->TOACCOUNTID)
		return 1;
	else
		return 0;
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_CATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	if((*m_item1)->CATEGID<(*m_item2)->CATEGID)
		return -1;
	else if((*m_item1)->CATEGID>(*m_item2)->CATEGID)
		return 1;
	else
		return 0;
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_NOTES(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	return (*m_item1)->NOTES.Cmp((*m_item2)->NOTES);
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_STATUS(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	return (*m_item1)->STATUS.Cmp((*m_item2)->STATUS);
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_TRANSACTIONNUMBER(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	return (*m_item1)->TRANSACTIONNUMBER.Cmp((*m_item2)->TRANSACTIONNUMBER);
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_TOTRANSAMOUNT(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	if((*m_item1)->TOTRANSAMOUNT<(*m_item2)->TOTRANSAMOUNT)
		return -1;
	else if((*m_item1)->TOTRANSAMOUNT>(*m_item2)->TOTRANSAMOUNT)
		return 1;
	else
		return 0;
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_ACCOUNTID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	if((*m_item1)->ACCOUNTID<(*m_item2)->ACCOUNTID)
		return -1;
	else if((*m_item1)->ACCOUNTID>(*m_item2)->ACCOUNTID)
		return 1;
	else
		return 0;
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_FOLLOWUPID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	if((*m_item1)->FOLLOWUPID<(*m_item2)->FOLLOWUPID)
		return -1;
	else if((*m_item1)->FOLLOWUPID>(*m_item2)->FOLLOWUPID)
		return 1;
	else
		return 0;
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_TRANSDATE(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	return (*m_item1)->TRANSDATE.Cmp((*m_item2)->TRANSDATE);
}

int CHECKINGACCOUNT_V1RowSet::CMPFUNC_TRANSID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	CHECKINGACCOUNT_V1Row** m_item1=(CHECKINGACCOUNT_V1Row**)item1;
	CHECKINGACCOUNT_V1Row** m_item2=(CHECKINGACCOUNT_V1Row**)item2;
	if((*m_item1)->TRANSID<(*m_item2)->TRANSID)
		return -1;
	else if((*m_item1)->TRANSID>(*m_item2)->TRANSID)
		return 1;
	else
		return 0;
}

CMPFUNC_proto CHECKINGACCOUNT_V1RowSet::GetCmpFunc(const wxString& var) const{
	if(var==wxT("TRANSAMOUNT"))
		return (CMPFUNC_proto)CMPFUNC_TRANSAMOUNT;
	else if(var==wxT("TRANSCODE"))
		return (CMPFUNC_proto)CMPFUNC_TRANSCODE;
	else if(var==wxT("SUBCATEGID"))
		return (CMPFUNC_proto)CMPFUNC_SUBCATEGID;
	else if(var==wxT("PAYEEID"))
		return (CMPFUNC_proto)CMPFUNC_PAYEEID;
	else if(var==wxT("TOACCOUNTID"))
		return (CMPFUNC_proto)CMPFUNC_TOACCOUNTID;
	else if(var==wxT("CATEGID"))
		return (CMPFUNC_proto)CMPFUNC_CATEGID;
	else if(var==wxT("NOTES"))
		return (CMPFUNC_proto)CMPFUNC_NOTES;
	else if(var==wxT("STATUS"))
		return (CMPFUNC_proto)CMPFUNC_STATUS;
	else if(var==wxT("TRANSACTIONNUMBER"))
		return (CMPFUNC_proto)CMPFUNC_TRANSACTIONNUMBER;
	else if(var==wxT("TOTRANSAMOUNT"))
		return (CMPFUNC_proto)CMPFUNC_TOTRANSAMOUNT;
	else if(var==wxT("ACCOUNTID"))
		return (CMPFUNC_proto)CMPFUNC_ACCOUNTID;
	else if(var==wxT("FOLLOWUPID"))
		return (CMPFUNC_proto)CMPFUNC_FOLLOWUPID;
	else if(var==wxT("TRANSDATE"))
		return (CMPFUNC_proto)CMPFUNC_TRANSDATE;
	else if(var==wxT("TRANSID"))
		return (CMPFUNC_proto)CMPFUNC_TRANSID;
	else 
	return (CMPFUNC_proto)CMPFUNC_default;
}



/** END ACTIVE RECORD ROW SET **/

////@@begin custom implementations



////@@end custom implementations