/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////


#ifndef __P_A_Y_E_E__V1_
#define __P_A_Y_E_E__V1_

////@@begin gen include
#include "wxActiveRecord.h"
#include <wx/wx.h>
#include <wx/string.h>
#include <wx/datetime.h>

////@@end gen include

////@@begin custom include
////@@end custom include

////@@begin gen forward
class PAYEE_V1;
class PAYEE_V1Row;
class PAYEE_V1RowSet;


////@@end gen forward

////@@begin custom forward
////@@end custom forward

////@@begin gen arClass
class PAYEE_V1: public wxSqliteActiveRecord{
protected:
	PAYEE_V1Row* RowFromResult(DatabaseResultSet* result);
public:
	PAYEE_V1();
	PAYEE_V1(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("PAYEE_V1"));
	PAYEE_V1(DatabaseLayer* database,const wxString& table=wxT("PAYEE_V1"));
	bool Create(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("PAYEE_V1"));
	
	PAYEE_V1Row* New();
	bool Delete(int key);

	
	PAYEE_V1Row* PAYEEID(int key);

	PAYEE_V1Row* Where(const wxString& whereClause);
	PAYEE_V1RowSet* WhereSet(const wxString& whereClause,const wxString& orderBy=wxEmptyString);
	PAYEE_V1RowSet* All(const wxString& orderBy=wxEmptyString); 

////@@begin custom arClass
public:


////@@end custom arClass
};
////@@end gen arClass

////@@begin gen arRow
class PAYEE_V1Row: public wxActiveRecordRow{
public:
	PAYEE_V1Row();
	PAYEE_V1Row(const PAYEE_V1Row& src);
	PAYEE_V1Row(PAYEE_V1* activeRecord);
	PAYEE_V1Row(DatabaseLayer* database,const wxString& table=wxT("PAYEE_V1"));
	PAYEE_V1Row& operator=(const PAYEE_V1Row& src);
	bool GetFromResult(DatabaseResultSet* result);
public:
	int SUBCATEGID;
	int PAYEEID;
	wxString PAYEENAME;
	int CATEGID;

public:
	
	
	bool Save();
	bool Delete();
	
	
////@@begin custom arRow
public:


////@@end custom arRow	

};
////@@end gen arRow

////@@begin gen arSet
class PAYEE_V1RowSet: public wxActiveRecordRowSet{
public:
	PAYEE_V1RowSet();
	PAYEE_V1RowSet(wxActiveRecord* activeRecord);
	PAYEE_V1RowSet(DatabaseLayer* database,const wxString& table=wxT("PAYEE_V1"));
	virtual PAYEE_V1Row* Item(unsigned long item);
	
	virtual bool SaveAll();
	
	
protected:
	static int CMPFUNC_SUBCATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_PAYEEID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_PAYEENAME(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_CATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_global(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	virtual CMPFUNC_proto GetCmpFunc(const wxString& var) const;

////@@begin custom arSet
public:


////@@end custom arSet
};
////@@end gen arSet

#endif /* __P_A_Y_E_E__V1_ */