/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////

#include "PAYEE_V1.h"

/** ACTIVE_RECORD **/
PAYEE_V1::PAYEE_V1():wxSqliteActiveRecord(){
}

PAYEE_V1::PAYEE_V1(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table):wxSqliteActiveRecord(name,server,user,password,table){
}

PAYEE_V1::PAYEE_V1(DatabaseLayer* database,const wxString& table):wxSqliteActiveRecord(database,table){
}

bool PAYEE_V1::Create(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table){
	return wxSqliteActiveRecord::Create(name,server,user,password,table);
}

PAYEE_V1Row* PAYEE_V1::RowFromResult(DatabaseResultSet* result){
	PAYEE_V1Row* row=new PAYEE_V1Row(this);
	
	row->GetFromResult(result);
	
	return row;
}

PAYEE_V1Row* PAYEE_V1::New(){
	PAYEE_V1Row* newRow=new PAYEE_V1Row(this);
	garbageRows.Add(newRow);
	return newRow;
}
bool PAYEE_V1::Delete(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE PAYEEID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}



PAYEE_V1Row* PAYEE_V1::PAYEEID(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("SELECT * FROM %s WHERE PAYEEID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		result->Next();
		PAYEE_V1Row* row=RowFromResult(result);
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return NULL;
	}
}




PAYEE_V1Row* PAYEE_V1::Where(const wxString& whereClause){
	try{
		wxString prepStatement = wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(!result->Next())
			return NULL;
		PAYEE_V1Row* row=RowFromResult(result);
		
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);						
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

PAYEE_V1RowSet* PAYEE_V1::WhereSet(const wxString& whereClause,const wxString& orderBy){
	PAYEE_V1RowSet* rowSet=new PAYEE_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}


PAYEE_V1RowSet* PAYEE_V1::All(const wxString& orderBy){
	PAYEE_V1RowSet* rowSet=new PAYEE_V1RowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s"),m_table.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		
		DatabaseResultSet* result= pStatement->ExecuteQuery();
		
		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);	
		return rowSet;
		
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

/** END ACTIVE RECORD **/

/** ACTIVE RECORD ROW **/

PAYEE_V1Row::PAYEE_V1Row():wxActiveRecordRow(){
	bool newRow=true;
}

PAYEE_V1Row::PAYEE_V1Row(PAYEE_V1* activeRecord):wxActiveRecordRow(activeRecord){
	bool newRow=true;
}

PAYEE_V1Row::PAYEE_V1Row(const PAYEE_V1Row& src){
	if(&src==this)
		return;
	newRow=src.newRow;
	
	SUBCATEGID=src.SUBCATEGID;
	PAYEEID=src.PAYEEID;
	PAYEENAME=src.PAYEENAME;
	CATEGID=src.CATEGID;

}

PAYEE_V1Row::PAYEE_V1Row(DatabaseLayer* database,const wxString& table):wxActiveRecordRow(database,table){
	newRow=true;
}
	

PAYEE_V1Row& PAYEE_V1Row::operator=(const PAYEE_V1Row& src){
	if(&src==this)
		return *this;
	newRow=src.newRow;
	
	SUBCATEGID=src.SUBCATEGID;
	PAYEEID=src.PAYEEID;
	PAYEENAME=src.PAYEENAME;
	CATEGID=src.CATEGID;


	return *this;
}

bool PAYEE_V1Row::GetFromResult(DatabaseResultSet* result){
	
	newRow=false;
		SUBCATEGID=result->GetResultInt(wxT("SUBCATEGID"));
	PAYEEID=result->GetResultInt(wxT("PAYEEID"));
	PAYEENAME=result->GetResultString(wxT("PAYEENAME"));
	CATEGID=result->GetResultInt(wxT("CATEGID"));


	return true;
}
	

bool PAYEE_V1Row::Save(){
	try{
		if(newRow){
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("INSERT INTO %s (SUBCATEGID,PAYEENAME,CATEGID) VALUES (?,?,?)"),m_table.c_str()));
			pStatement->SetParamInt(1,SUBCATEGID);
			pStatement->SetParamString(2,PAYEENAME);
			pStatement->SetParamInt(3,CATEGID);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

			
			newRow=false;
		}
		else{
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("UPDATE %s SET SUBCATEGID=?,PAYEENAME=?,CATEGID=? WHERE PAYEEID=?"),m_table.c_str()));
			pStatement->SetParamInt(1,SUBCATEGID);
			pStatement->SetParamInt(4,PAYEEID);
			pStatement->SetParamString(2,PAYEENAME);
			pStatement->SetParamInt(3,CATEGID);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

		}
		
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		wxActiveRecord::ProcessException(e);
		return false;
	}
}

bool PAYEE_V1Row::Delete(){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE PAYEEID=?"),m_table.c_str()));
		pStatement->SetParamInt(1,PAYEEID);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}





/** END ACTIVE RECORD ROW **/

/** ACTIVE RECORD ROW SET **/

PAYEE_V1RowSet::PAYEE_V1RowSet():wxActiveRecordRowSet(){
}

PAYEE_V1RowSet::PAYEE_V1RowSet(wxActiveRecord* activeRecord):wxActiveRecordRowSet(activeRecord){
}

PAYEE_V1RowSet::PAYEE_V1RowSet(DatabaseLayer* database,const wxString& table):wxActiveRecordRowSet(database,table){
}

PAYEE_V1Row* PAYEE_V1RowSet::Item(unsigned long item){
	return (PAYEE_V1Row*)wxActiveRecordRowSet::Item(item);
}


bool PAYEE_V1RowSet::SaveAll(){
	try{
		m_database->BeginTransaction();
		for(unsigned long i=0;i<Count();i++)
			Item(i)->Save();
		m_database->Commit();
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		m_database->RollBack();
		wxActiveRecord::ProcessException(e);
		return false;
	}
}


int PAYEE_V1RowSet::CMPFUNC_SUBCATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	PAYEE_V1Row** m_item1=(PAYEE_V1Row**)item1;
	PAYEE_V1Row** m_item2=(PAYEE_V1Row**)item2;
	if((*m_item1)->SUBCATEGID<(*m_item2)->SUBCATEGID)
		return -1;
	else if((*m_item1)->SUBCATEGID>(*m_item2)->SUBCATEGID)
		return 1;
	else
		return 0;
}

int PAYEE_V1RowSet::CMPFUNC_PAYEEID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	PAYEE_V1Row** m_item1=(PAYEE_V1Row**)item1;
	PAYEE_V1Row** m_item2=(PAYEE_V1Row**)item2;
	if((*m_item1)->PAYEEID<(*m_item2)->PAYEEID)
		return -1;
	else if((*m_item1)->PAYEEID>(*m_item2)->PAYEEID)
		return 1;
	else
		return 0;
}

int PAYEE_V1RowSet::CMPFUNC_PAYEENAME(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	PAYEE_V1Row** m_item1=(PAYEE_V1Row**)item1;
	PAYEE_V1Row** m_item2=(PAYEE_V1Row**)item2;
	return (*m_item1)->PAYEENAME.Cmp((*m_item2)->PAYEENAME);
}

int PAYEE_V1RowSet::CMPFUNC_CATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	PAYEE_V1Row** m_item1=(PAYEE_V1Row**)item1;
	PAYEE_V1Row** m_item2=(PAYEE_V1Row**)item2;
	if((*m_item1)->CATEGID<(*m_item2)->CATEGID)
		return -1;
	else if((*m_item1)->CATEGID>(*m_item2)->CATEGID)
		return 1;
	else
		return 0;
}

CMPFUNC_proto PAYEE_V1RowSet::GetCmpFunc(const wxString& var) const{
	if(var==wxT("SUBCATEGID"))
		return (CMPFUNC_proto)CMPFUNC_SUBCATEGID;
	else if(var==wxT("PAYEEID"))
		return (CMPFUNC_proto)CMPFUNC_PAYEEID;
	else if(var==wxT("PAYEENAME"))
		return (CMPFUNC_proto)CMPFUNC_PAYEENAME;
	else if(var==wxT("CATEGID"))
		return (CMPFUNC_proto)CMPFUNC_CATEGID;
	else 
	return (CMPFUNC_proto)CMPFUNC_default;
}



/** END ACTIVE RECORD ROW SET **/

////@@begin custom implementations



////@@end custom implementations