/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////


#ifndef __S_T_O_C_K__V1_
#define __S_T_O_C_K__V1_

////@@begin gen include
#include "wxActiveRecord.h"
#include <wx/wx.h>
#include <wx/string.h>
#include <wx/datetime.h>

////@@end gen include

////@@begin custom include
////@@end custom include

////@@begin gen forward
class STOCK_V1;
class STOCK_V1Row;
class STOCK_V1RowSet;


////@@end gen forward

////@@begin custom forward
////@@end custom forward

////@@begin gen arClass
class STOCK_V1: public wxSqliteActiveRecord{
protected:
	STOCK_V1Row* RowFromResult(DatabaseResultSet* result);
public:
	STOCK_V1();
	STOCK_V1(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("STOCK_V1"));
	STOCK_V1(DatabaseLayer* database,const wxString& table=wxT("STOCK_V1"));
	bool Create(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("STOCK_V1"));
	
	STOCK_V1Row* New();
	bool Delete(int key);

	
	STOCK_V1Row* STOCKID(int key);

	STOCK_V1Row* Where(const wxString& whereClause);
	STOCK_V1RowSet* WhereSet(const wxString& whereClause,const wxString& orderBy=wxEmptyString);
	STOCK_V1RowSet* All(const wxString& orderBy=wxEmptyString); 

////@@begin custom arClass
public:


////@@end custom arClass
};
////@@end gen arClass

////@@begin gen arRow
class STOCK_V1Row: public wxActiveRecordRow{
public:
	STOCK_V1Row();
	STOCK_V1Row(const STOCK_V1Row& src);
	STOCK_V1Row(STOCK_V1* activeRecord);
	STOCK_V1Row(DatabaseLayer* database,const wxString& table=wxT("STOCK_V1"));
	STOCK_V1Row& operator=(const STOCK_V1Row& src);
	bool GetFromResult(DatabaseResultSet* result);
public:
	wxString NUMSHARES;
	wxString SYMBOL;
	wxString HELDAT;
	wxString NOTES;
	int STOCKID;
	wxString STOCKNAME;
	wxString PURCHASEPRICE;
	wxString CURRENTPRICE;
	wxString COMMISSION;
	wxString PURCHASEDATE;
	wxString VALUE;

public:
	
	
	bool Save();
	bool Delete();
	
	
////@@begin custom arRow
public:


////@@end custom arRow	

};
////@@end gen arRow

////@@begin gen arSet
class STOCK_V1RowSet: public wxActiveRecordRowSet{
public:
	STOCK_V1RowSet();
	STOCK_V1RowSet(wxActiveRecord* activeRecord);
	STOCK_V1RowSet(DatabaseLayer* database,const wxString& table=wxT("STOCK_V1"));
	virtual STOCK_V1Row* Item(unsigned long item);
	
	virtual bool SaveAll();
	
	
protected:
	static int CMPFUNC_NUMSHARES(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_SYMBOL(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_HELDAT(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_NOTES(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_STOCKID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_STOCKNAME(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_PURCHASEPRICE(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_CURRENTPRICE(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_COMMISSION(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_PURCHASEDATE(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_VALUE(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_global(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	virtual CMPFUNC_proto GetCmpFunc(const wxString& var) const;

////@@begin custom arSet
public:


////@@end custom arSet
};
////@@end gen arSet

#endif /* __S_T_O_C_K__V1_ */