/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////


#ifndef __S_U_B_C_A_T_E_G_O_R_Y__V1_
#define __S_U_B_C_A_T_E_G_O_R_Y__V1_

////@@begin gen include
#include "wxActiveRecord.h"
#include <wx/wx.h>
#include <wx/string.h>
#include <wx/datetime.h>
#include "CATEGORY_V1.h"

////@@end gen include

////@@begin custom include
////@@end custom include

////@@begin gen forward
class SUBCATEGORY_V1;
class SUBCATEGORY_V1Row;
class SUBCATEGORY_V1RowSet;

class CATEGORY_V1;
class CATEGORY_V1Row;
class CATEGORY_V1RowSet;

////@@end gen forward

////@@begin custom forward
////@@end custom forward

////@@begin gen arClass
class SUBCATEGORY_V1: public wxSqliteActiveRecord{
protected:
	SUBCATEGORY_V1Row* RowFromResult(DatabaseResultSet* result);
public:
	SUBCATEGORY_V1();
	SUBCATEGORY_V1(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("SUBCATEGORY_V1"));
	SUBCATEGORY_V1(DatabaseLayer* database,const wxString& table=wxT("SUBCATEGORY_V1"));
	bool Create(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("SUBCATEGORY_V1"));
	
	SUBCATEGORY_V1Row* New();
	bool Delete(int key);

	
	SUBCATEGORY_V1Row* SUBCATEGID(int key);

	SUBCATEGORY_V1Row* Where(const wxString& whereClause);
	SUBCATEGORY_V1RowSet* WhereSet(const wxString& whereClause,const wxString& orderBy=wxEmptyString);
	SUBCATEGORY_V1RowSet* All(const wxString& orderBy=wxEmptyString); 

////@@begin custom arClass
public:


////@@end custom arClass
};
////@@end gen arClass

////@@begin gen arRow
class SUBCATEGORY_V1Row: public wxActiveRecordRow{
public:
	SUBCATEGORY_V1Row();
	SUBCATEGORY_V1Row(const SUBCATEGORY_V1Row& src);
	SUBCATEGORY_V1Row(SUBCATEGORY_V1* activeRecord);
	SUBCATEGORY_V1Row(DatabaseLayer* database,const wxString& table=wxT("SUBCATEGORY_V1"));
	SUBCATEGORY_V1Row& operator=(const SUBCATEGORY_V1Row& src);
	bool GetFromResult(DatabaseResultSet* result);
public:
	wxString SUBCATEGNAME;
	int SUBCATEGID;
	int CATEGID;

public:
	CATEGORY_V1Row* GetCATEGORY_V1();

	
	bool Save();
	bool Delete();
	
	
////@@begin custom arRow
public:


////@@end custom arRow	

};
////@@end gen arRow

////@@begin gen arSet
class SUBCATEGORY_V1RowSet: public wxActiveRecordRowSet{
public:
	SUBCATEGORY_V1RowSet();
	SUBCATEGORY_V1RowSet(wxActiveRecord* activeRecord);
	SUBCATEGORY_V1RowSet(DatabaseLayer* database,const wxString& table=wxT("SUBCATEGORY_V1"));
	virtual SUBCATEGORY_V1Row* Item(unsigned long item);
	
	virtual bool SaveAll();
	
	
protected:
	static int CMPFUNC_SUBCATEGNAME(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_SUBCATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_CATEGID(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_global(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	virtual CMPFUNC_proto GetCmpFunc(const wxString& var) const;

////@@begin custom arSet
public:


////@@end custom arSet
};
////@@end gen arSet

#endif /* __S_U_B_C_A_T_E_G_O_R_Y__V1_ */