/////////////////////////////////////////////////////////////////////////////
// Name:        filtertransdialog.cpp
// Purpose:     
// Author:      
// Modified by: 
// Created:     08/30/06 07:23:20
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 08/30/06 07:23:20

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma implementation "filtertransdialog.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

#include "filtertransdialog.h"

#include "defs.h"
#include "util.h"
#include "dbwrapper.h"
#include "mmcoredb.h"
#include "categdialog.h"
#include "payeedialog.h"
#include "paths.h"

#include <algorithm>
#include <vector>

bool sortTransactionsByDate1( boost::shared_ptr<mmBankTransaction> elem1, 
                             boost::shared_ptr<mmBankTransaction> elem2 )
{
   return elem1->date_ < elem2->date_;
}

IMPLEMENT_DYNAMIC_CLASS( mmFilterTransactionsDialog, wxDialog )

BEGIN_EVENT_TABLE( mmFilterTransactionsDialog, wxDialog )

    EVT_CHECKBOX( ID_CHECKBOXACCOUNT,   mmFilterTransactionsDialog::OnCheckboxaccountClick )
    EVT_CHECKBOX( ID_CHECKBOXDATERANGE, mmFilterTransactionsDialog::OnCheckboxDateRangeClick )
    EVT_CHECKBOX( ID_CHECKBOXPAYEE,     mmFilterTransactionsDialog::OnCheckboxpayeeClick )
    EVT_CHECKBOX( ID_CHECKBOXCATEGORY,  mmFilterTransactionsDialog::OnCheckboxcategoryClick )
    EVT_CHECKBOX( ID_CHECKBOXSTATUS,    mmFilterTransactionsDialog::OnCheckboxstatusClick )
    EVT_CHECKBOX( ID_CHECKBOXTYPE,      mmFilterTransactionsDialog::OnCheckboxtypeClick )
    EVT_CHECKBOX( ID_CHECKBOXAMOUNTRANGE, mmFilterTransactionsDialog::OnCheckboxamountrangeClick )
    EVT_CHECKBOX( ID_CHECKBOXNOTES,     mmFilterTransactionsDialog::OnCheckboxnotesClick )
    EVT_BUTTON( wxID_OK,            mmFilterTransactionsDialog::OnButtonokClick )
    EVT_BUTTON( wxID_CANCEL,        mmFilterTransactionsDialog::OnButtoncancelClick )
    EVT_BUTTON(ID_BUTTONPAYEE,          mmFilterTransactionsDialog::OnPayee)
    EVT_BUTTON(ID_BUTTONCATEGORY,       mmFilterTransactionsDialog::OnCategs)
    EVT_CHECKBOX( ID_CHECKBOXTRANSNUM,  mmFilterTransactionsDialog::OnCheckboxTransNumberClick )

END_EVENT_TABLE()

mmFilterTransactionsDialog::mmFilterTransactionsDialog( )
{
}

mmFilterTransactionsDialog::mmFilterTransactionsDialog(std::vector< boost::shared_ptr<mmBankTransaction> >* trans,
                                                       mmCoreDB* core,
                                                       wxWindow* parent, wxWindowID id, 
                                                       const wxString& caption, 
                                                       const wxPoint& pos, const wxSize& size, 
                                                       long style )
: trans_(trans), core_(core), db_(core->db_.get())
, categID_(-1), subcategID_(-1), payeeID_(-1), refAccountID_(-1)
{
    Create(parent, id, caption, pos, size, style);
}

bool mmFilterTransactionsDialog::Create( wxWindow* parent, wxWindowID id, 
                                        const wxString& caption, const wxPoint& pos, 
                                        const wxSize& size, long style )
{
    accountCheckBox = NULL;
    accountDropDown = NULL;
    dateRangeCheckBox = NULL;
    fromDateCtrl = NULL;
    toDateControl = NULL;
    payeeCheckBox = NULL;
    btnPayee = NULL;
    categoryCheckBox = NULL;
    btnCategory = NULL;
    statusCheckBox = NULL;
    choiceStatus = NULL;
    typeCheckBox = NULL;
    choiceType = NULL;
    amountRangeCheckBox = NULL;
    amountMinEdit = NULL;
    amountMaxEdit = NULL;
    notesCheckBox = NULL;
    notesEdit = NULL;

    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    GetSizer()->Fit(this);
    GetSizer()->SetSizeHints(this);

    SetIcon(mmex::getProgramIcon());

    Centre();
    return true;
}

void mmFilterTransactionsDialog::CreateControls()
{    
    int fieldWidth = 210;

    wxSizerFlags flags;
    flags.Align(wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL).Border(wxALL, 5);

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxHORIZONTAL);
    this->SetSizer(itemBoxSizer2);
    
    wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxVERTICAL);
    itemBoxSizer2->Add(itemBoxSizer3, flags);

    wxStaticBox* itemStaticBoxSizer4Static = new wxStaticBox(this, wxID_ANY, _(" Specify "));
    wxStaticBoxSizer* itemStaticBoxSizer4 = new wxStaticBoxSizer(itemStaticBoxSizer4Static, wxVERTICAL);
    itemBoxSizer3->Add(itemStaticBoxSizer4, flags);
    
    this->SetSizer(itemBoxSizer2);

    /******************************************************************************
     Items Panel
    *******************************************************************************/
    wxPanel* itemPanel = new wxPanel( this, ID_PANEL11, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL );
    itemStaticBoxSizer4->Add(itemPanel, 1, wxGROW|wxALL, 5);

    wxFlexGridSizer* itemPanelSizer = new wxFlexGridSizer(0, 2, 10, 10);
    itemPanel->SetSizer(itemPanelSizer);

    //--Start of Row --------------------------------------------------------
    accountCheckBox = new wxCheckBox( itemPanel, ID_CHECKBOXACCOUNT, _("Account:"), 
                                      wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    accountCheckBox->SetValue(FALSE);
    itemPanelSizer->Add(accountCheckBox, flags.Border(wxALL, 0));

    wxArrayString as = core_->getAccountsName();
   
    accountDropDown = new wxChoice(itemPanel, ID_CHOICE4, wxDefaultPosition, wxSize(fieldWidth,-1), as, 0 );
    accountDropDown->SetSelection(0);
    itemPanelSizer->Add(accountDropDown, flags);
    //--End of Row --------------------------------------------------------

    dateRangeCheckBox = new wxCheckBox( itemPanel, ID_CHECKBOXDATERANGE, _("Date Range:"),
                                        wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    dateRangeCheckBox->SetValue(FALSE);
    itemPanelSizer->Add(dateRangeCheckBox, flags);

    fromDateCtrl = new wxDatePickerCtrl( itemPanel, ID_CHOICE5, wxDefaultDateTime, 
                                         wxDefaultPosition, wxDefaultSize, wxDP_DROPDOWN);
    toDateControl = new wxDatePickerCtrl( itemPanel, ID_CHOICE6, wxDefaultDateTime, 
                                          wxDefaultPosition, wxDefaultSize, wxDP_DROPDOWN);

    wxBoxSizer* dateSizer = new wxBoxSizer(wxHORIZONTAL);
    dateSizer->Add(fromDateCtrl, flags);
    dateSizer->AddSpacer(10);
    dateSizer->Add(toDateControl, flags);
    itemPanelSizer->Add(dateSizer, flags);
    //--End of Row --------------------------------------------------------
    
    payeeCheckBox = new wxCheckBox( itemPanel, ID_CHECKBOXPAYEE, _("Payee:"), 
                                    wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    payeeCheckBox->SetValue(FALSE);
    itemPanelSizer->Add(payeeCheckBox, flags);

    btnPayee = new wxButton( itemPanel, ID_BUTTONPAYEE, _("Select Payee"), 
                             wxDefaultPosition, wxSize(fieldWidth,-1), 0 );
    itemPanelSizer->Add(btnPayee, flags);
    //--End of Row --------------------------------------------------------

    categoryCheckBox = new wxCheckBox( itemPanel, ID_CHECKBOXCATEGORY, _("Category:"), 
                                       wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    categoryCheckBox->SetValue(FALSE);
    itemPanelSizer->Add(categoryCheckBox, flags);

    btnCategory = new wxButton( itemPanel, ID_BUTTONCATEGORY, _("Select Category"), 
                                wxDefaultPosition, wxSize(fieldWidth,-1), 0 );
    itemPanelSizer->Add(btnCategory, flags);
    //--End of Row --------------------------------------------------------

    statusCheckBox = new wxCheckBox( itemPanel, ID_CHECKBOXSTATUS, _("Status:"), 
                                     wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    statusCheckBox->SetValue(FALSE);
    itemPanelSizer->Add(statusCheckBox, flags);

    wxString transaction_status[] = 
    {
        wxTRANSLATE("None"),
        wxTRANSLATE("Reconciled"),
        wxTRANSLATE("Void"),
        wxTRANSLATE("Follow up"),
        wxTRANSLATE("Duplicate")
    };

    choiceStatus = new wxChoice( itemPanel, ID_CHOICE7, wxDefaultPosition, wxDefaultSize);
    for(size_t i = 0; i < sizeof(transaction_status)/sizeof(wxString); ++i)
        choiceStatus->Append(wxGetTranslation(transaction_status[i]),
        new wxStringClientData(transaction_status[i]));
    itemPanelSizer->Add(choiceStatus, flags);
    choiceStatus->SetSelection(0);
    choiceStatus->SetToolTip(_("Specify the status for the transaction"));
    //--End of Row --------------------------------------------------------

    typeCheckBox = new wxCheckBox( itemPanel, ID_CHECKBOXTYPE, _("Type:"), 
                                   wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    typeCheckBox->SetValue(FALSE);
    
    wxArrayString choiceTypeStrings;
    choiceTypeStrings.Add(_("Withdrawal"));
    choiceTypeStrings.Add(_("Deposit"));
    choiceTypeStrings.Add(_("Transfer"));
    choiceType = new wxChoice( itemPanel, ID_CHOICE8, wxDefaultPosition, wxDefaultSize, choiceTypeStrings);

    choiceType->SetSelection(0);
    choiceType->Show(false);
    choiceType->SetToolTip(_("Specify the type of transaction."));

    wxBoxSizer* typeSizer = new wxBoxSizer(wxVERTICAL);
    cbTypeWithdrawal_ = new wxCheckBox( itemPanel, ID_DIALOG_TRANSFILTER_CB_TYPE_WITHDRAWAL,
        _("Withdrawal"), wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    cbTypeWithdrawal_->Enable(false);
    cbTypeDeposit_ = new wxCheckBox( itemPanel, ID_DIALOG_TRANSFILTER_CB_TYPE_DEPOSIT,
        _("Deposit"), wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    cbTypeDeposit_->Enable(false);
    cbTypeTransfer_ = new wxCheckBox( itemPanel, ID_DIALOG_TRANSFILTER_CB_TYPE_TRANSFER,
        _("Transfer"), wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    cbTypeTransfer_->Enable(false);

    itemPanelSizer->Add(typeCheckBox, flags);
    itemPanelSizer->Add(typeSizer, flags);
    typeSizer ->Add(choiceType, flags);
    typeSizer ->Add(cbTypeWithdrawal_, flags);
    typeSizer ->Add(cbTypeDeposit_, flags);
    typeSizer ->Add(cbTypeTransfer_, flags);
    
    //--End of Row --------------------------------------------------------

    amountRangeCheckBox = new wxCheckBox(itemPanel, ID_CHECKBOXAMOUNTRANGE, _("Amount Range:"), 
                                         wxDefaultPosition, wxDefaultSize, wxCHK_2STATE);
    amountRangeCheckBox->SetValue(FALSE);
    itemPanelSizer->Add(amountRangeCheckBox, flags);

    amountMinEdit = new wxTextCtrl( itemPanel, ID_TEXTCTRL13, (""),
        wxDefaultPosition, wxSize(fieldWidth/2-5,-1), wxALIGN_RIGHT|wxTE_PROCESS_ENTER,
        wxFloatingPointValidator<float>(2));
    amountMaxEdit = new wxTextCtrl( itemPanel, ID_TEXTCTRL14, (""),
        wxDefaultPosition, wxSize(fieldWidth/2-5,-1), wxALIGN_RIGHT|wxTE_PROCESS_ENTER,
        wxFloatingPointValidator<float>(2) );

    wxBoxSizer* amountSizer = new wxBoxSizer(wxHORIZONTAL);
    amountSizer->Add(amountMinEdit, flags);
    amountSizer->AddSpacer(10);
    amountSizer->Add(amountMaxEdit, flags);
    itemPanelSizer->Add(amountSizer, flags);
    //--End of Row --------------------------------------------------------

    transNumberCheckBox = new wxCheckBox( itemPanel, ID_CHECKBOXTRANSNUM, _("Number:"),
                                          wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    transNumberCheckBox->SetValue(FALSE);
    itemPanelSizer->Add(transNumberCheckBox, flags);

    transNumberEdit = new wxTextCtrl( itemPanel, ID_TEXTTRANSNUM, "", wxDefaultPosition, wxSize(fieldWidth,-1), 0 );
    itemPanelSizer->Add(transNumberEdit, flags);
    //--End of Row --------------------------------------------------------

    notesCheckBox = new wxCheckBox( itemPanel, ID_CHECKBOXNOTES, _("Notes:"), 
                                    wxDefaultPosition, wxDefaultSize, wxCHK_2STATE );
    notesCheckBox->SetValue(FALSE);
    itemPanelSizer->Add(notesCheckBox, flags);

    notesEdit = new wxTextCtrl( itemPanel, ID_TEXTCTRL15, "", wxDefaultPosition, wxSize(fieldWidth,-1), 0 );
    itemPanelSizer->Add(notesEdit, flags);
    //--End of Row --------------------------------------------------------

    /******************************************************************************
     Button Panel with OK/Cancel buttons   
    *******************************************************************************/
    wxPanel* buttonPanel = new wxPanel( this, ID_PANEL12, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL );
    itemBoxSizer3->Add(buttonPanel, flags.Center().Border(wxALL, 5));

    wxBoxSizer* buttonPanelSizer = new wxBoxSizer(wxHORIZONTAL);
    buttonPanel->SetSizer(buttonPanelSizer);

    wxButton* itemButton30 = new wxButton( buttonPanel, wxID_OK);
    buttonPanelSizer->Add(itemButton30, flags);

    wxButton* itemButtonCancel = new wxButton( buttonPanel, wxID_CANCEL);
    buttonPanelSizer->Add(itemButtonCancel, flags);
    itemButtonCancel->SetFocus();
    
    // disable all controls at startup
    accountDropDown->Enable(false);
    fromDateCtrl->Enable(false);
    toDateControl->Enable(false);
    btnPayee->Enable(false);
    btnCategory->Enable(false);
    choiceStatus->Enable(false);
    choiceType->Enable(false);
    amountMinEdit->Enable(false);
    amountMaxEdit->Enable(false);
    notesEdit->Enable(false);
    transNumberEdit->Enable(false);
}   

/*!
 * Should we show tooltips?
 */

void mmFilterTransactionsDialog::OnCheckboxaccountClick( wxCommandEvent& /*event*/ )
{
    accountDropDown->Enable(accountCheckBox->GetValue());
}

void mmFilterTransactionsDialog::OnCheckboxDateRangeClick( wxCommandEvent& /*event*/ )
{
    fromDateCtrl->Enable(this->dateRangeCheckBox->GetValue());
    toDateControl->Enable(this->dateRangeCheckBox->GetValue());
}

void mmFilterTransactionsDialog::OnCheckboxpayeeClick( wxCommandEvent& /*event*/ )
{
    btnPayee->Enable(this->payeeCheckBox->GetValue());
}

void mmFilterTransactionsDialog::OnCheckboxcategoryClick( wxCommandEvent& /*event*/ )
{
    btnCategory->Enable(this->categoryCheckBox->GetValue());
}

void mmFilterTransactionsDialog::OnCheckboxstatusClick( wxCommandEvent& /*event*/ )
{
    choiceStatus->Enable(statusCheckBox->GetValue());
}

void mmFilterTransactionsDialog::OnCheckboxtypeClick( wxCommandEvent& /*event*/ )
{
    choiceType->Enable(typeCheckBox->GetValue());
    cbTypeWithdrawal_->Enable(typeCheckBox->GetValue());
    cbTypeDeposit_->Enable(typeCheckBox->GetValue());
    cbTypeTransfer_->Enable(typeCheckBox->GetValue());

}

void mmFilterTransactionsDialog::OnCheckboxamountrangeClick( wxCommandEvent& /*event*/ )
{
    amountMinEdit->Enable(amountRangeCheckBox->GetValue());
    amountMaxEdit->Enable(amountRangeCheckBox->GetValue());
}

void mmFilterTransactionsDialog::OnCheckboxnotesClick( wxCommandEvent& /*event*/ )
{
    notesEdit->Enable(notesCheckBox->GetValue());
}

void mmFilterTransactionsDialog::OnCheckboxTransNumberClick( wxCommandEvent& /*event*/ )
{
    transNumberEdit->Enable(transNumberCheckBox->GetValue());
}

void mmFilterTransactionsDialog::OnButtonokClick( wxCommandEvent& /*event*/ )
{
    std::vector< boost::shared_ptr<mmBankTransaction> >::const_iterator i;
    for (i = core_->bTransactionList_.transactions_.begin(); i != core_->bTransactionList_.transactions_.end(); i++ )
    {
        boost::shared_ptr<mmBankTransaction> pBankTransaction = *i;
        if (pBankTransaction)
        {
            /* START FILTERING TRANSACTIONS */
            if (accountCheckBox->GetValue())
            {
                wxString acctName = accountDropDown->GetStringSelection();
                int fromAccountID = core_->getAccountID(acctName);
                refAccountID_ = fromAccountID;
                refAccountStr_ = acctName;

                if ((pBankTransaction->accountID_ != fromAccountID) && (pBankTransaction->toAccountID_ != fromAccountID))
                    continue; // skip
            }

            if (dateRangeCheckBox->GetValue())
            {
                wxDateTime dtBegin = fromDateCtrl->GetValue();
                wxDateTime dtEnd = toDateControl->GetValue();

                if ((dtBegin == dtEnd) && (dtBegin.IsSameDate(pBankTransaction->date_)))
                {

                }
                else
                {
                    if (!pBankTransaction->date_.IsBetween(dtBegin, dtEnd))
                        continue; // skip
                }
            }

            if (payeeCheckBox->GetValue() && (payeeID_ != -1))
            {
                if (pBankTransaction->payeeID_ != payeeID_)
                    continue; // skip
            }

            if (categoryCheckBox->GetValue() && (categID_ != -1))
            {
                bool ignoreSubCateg = false;
                if (subcategID_ == -1)
                    ignoreSubCateg = true;
                if (!pBankTransaction->containsCategory(categID_, subcategID_, ignoreSubCateg))
                {
                    pBankTransaction->reportCategAmountStr_ = ("");
                    continue;
                }

                if (pBankTransaction->splitEntries_->numEntries() > 0)
                {
                    pBankTransaction->reportCategAmount_ = fabs(pBankTransaction->getAmountForSplit(categID_, subcategID_));

                    boost::shared_ptr<mmCurrency> pCurrencyPtr = core_->getCurrencyWeakPtr(pBankTransaction->accountID_).lock();
                    wxASSERT(pCurrencyPtr);
                    mmex::formatDoubleToCurrencyEdit(pBankTransaction->reportCategAmount_, pBankTransaction->reportCategAmountStr_);
                }
                else
                {
                    pBankTransaction->reportCategAmount_ = -1;
                    pBankTransaction->reportCategAmountStr_.clear();
                }
            }

            if (statusCheckBox->GetValue())
            {
                wxStringClientData* status_obj = (wxStringClientData *)choiceStatus->GetClientObject(choiceStatus->GetSelection());
                wxString data;
                wxString bank_trans_status = pBankTransaction->status_;
                bank_trans_status = (bank_trans_status.IsEmpty() ? "N" : bank_trans_status.Left(1));
                if (status_obj) data = status_obj->GetData().Left(1);

                if (data != bank_trans_status)
                    continue; //skip
            }

            if (typeCheckBox->GetValue())
            {
                wxString transCode = pBankTransaction->transType_;
                wxString transCodeSelectedWithdraval=("-");
                wxString transCodeSelectedDeposit=("-");
                wxString transCodeSelectedTransfer=("-");
                if (cbTypeWithdrawal_->GetValue())
                    transCodeSelectedWithdraval = TRANS_TYPE_WITHDRAWAL_STR;
                if (cbTypeDeposit_->GetValue())
                    transCodeSelectedDeposit = TRANS_TYPE_DEPOSIT_STR;
                if (cbTypeTransfer_->GetValue())
                    transCodeSelectedTransfer = TRANS_TYPE_TRANSFER_STR;

                if (transCodeSelectedWithdraval != transCode 
                    && transCodeSelectedDeposit != transCode
                    && transCodeSelectedTransfer != transCode)
                    continue; // skip
            }

            if (amountRangeCheckBox->GetValue())
            {
                wxString minamt = amountMinEdit->GetValue();
                wxString maxamt = amountMaxEdit->GetValue();
                if (!minamt.IsEmpty())
                {
                    double amount;
                    if (!mmex::formatCurrencyToDouble(minamt, amount) || (amount < 0.0))
                    {
                        mmShowErrorMessage(this, _("Invalid Amount Entered "), _("Error"));
                        return;
                    }

                    if (pBankTransaction->amt_ < amount)
                        continue; // skip
                }

                if (!maxamt.IsEmpty())
                {
                    double amount;
                    if (!mmex::formatCurrencyToDouble(maxamt, amount) || (amount < 0.0))
                    {
                        mmShowErrorMessage(this, _("Invalid Amount Entered "), _("Error"));
                        return;
                    }

                    if (pBankTransaction->amt_ > amount)
                        continue; // skip
                }
            }

            if (notesCheckBox->GetValue())
            {
                wxString notes = notesEdit->GetValue().Trim().Lower();
                wxString orig = pBankTransaction->notes_.Lower();
                if (!orig.Matches(notes+"*"))
                    continue;
            }
        
            if (transNumberCheckBox->GetValue())
            {
                wxString transNumber = transNumberEdit->GetValue().Trim().Lower();
                wxString orig = pBankTransaction->transNum_.Lower();
                if (!orig.Contains(transNumber))
                    continue;
            }

            (*trans_).push_back(pBankTransaction);
        }
    }

    std::sort((*trans_).begin(), (*trans_).end(), sortTransactionsByDate1);
    
    EndModal(wxID_OK);
}

void mmFilterTransactionsDialog::OnButtoncancelClick( wxCommandEvent& /*event*/ )
{
    EndModal(wxID_CANCEL);
}

void mmFilterTransactionsDialog::OnCategs(wxCommandEvent& /*event*/)
{
    mmCategDialog dlg(core_, this);
    dlg.ShowModal();

    if (dlg.categID_ == -1)
    {
        // check if categ and subcateg are now invalid
        wxString catName = core_->getCategoryName(categID_);
        if (catName.IsEmpty())
        {
            // cannot find category
            categID_ = -1;
            subcategID_ = -1;
            btnCategory->SetLabel(_("Select Category"));
            return;
        }

        if (dlg.subcategID_ != -1)
        {
            wxString subcatName = mmDBWrapper::getSubCategoryName(db_, categID_, subcategID_);
            if (subcatName.IsEmpty())
            {
                subcategID_ = -1;
                btnCategory->SetLabel(catName);
                return;
            }
        }
        else
        {
            catName.Replace(("&"), ("&&"));
            btnCategory->SetLabel(catName);
        }
        
        return;
    }
    
    categID_ = dlg.categID_;
    subcategID_ = dlg.subcategID_;

    wxString catName = core_->getCategoryName(dlg.categID_);
    catName.Replace(("&"), ("&&"));
    wxString categString = catName;

    if (dlg.subcategID_ != -1)
    {
        wxString subcatName = mmDBWrapper::getSubCategoryName(db_,
            dlg.categID_, dlg.subcategID_);
        subcatName.Replace(("&"), ("&&"));
        categString += (" : ");
        categString += subcatName;
    }
    
     btnCategory->SetLabel(categString);
}

void mmFilterTransactionsDialog::OnPayee(wxCommandEvent& /*event*/)
{
    mmPayeeDialog dlg(this, core_);
    if ( dlg.ShowModal() == wxID_OK )
    {
        payeeID_ = dlg.getPayeeId();
        if (payeeID_ == -1)
        {
            btnPayee->SetLabel(_("Select Payee"));
            return;
        }
        wxString payeeName = mmDBWrapper::getPayee(db_, payeeID_, categID_, subcategID_);
        btnPayee->SetLabel(mmReadyDisplayString(payeeName));
    }
}

bool mmFilterTransactionsDialog::getDateRange(wxDateTime& startDate, wxDateTime& endDate)
{
    bool validDates = false;
    if (dateRangeCheckBox->IsChecked())
    {
        startDate = fromDateCtrl->GetValue();
        endDate = toDateControl->GetValue();
        validDates = true;
    }
    return validDates;
}

wxString mmFilterTransactionsDialog::userDateRangeStr()
{
    wxString dateStr;
    if (dateRangeCheckBox->IsChecked())
    {
        wxString dtBegin = mmGetDateForDisplay(db_, fromDateCtrl->GetValue());
        wxString dtEnd = mmGetDateForDisplay(db_, toDateControl->GetValue());
        dateStr = wxString::Format(_("From %s to %s"), dtBegin , dtEnd);
    }
    return dateStr;
}

wxString mmFilterTransactionsDialog::userPayeeStr()
{
    wxString payeeStr;
    if (payeeCheckBox->IsChecked())
    {
        payeeStr = btnPayee->GetLabelText();
    }
    return payeeStr;
}

wxString mmFilterTransactionsDialog::userCategoryStr()
{
    wxString catStr;
    if (categoryCheckBox->IsChecked())
    {
        catStr = btnCategory->GetLabelText();
    }
    return catStr;
}

wxString mmFilterTransactionsDialog::userStatusStr()
{
    wxString statusStr;
    if (statusCheckBox->IsChecked())
    {
        statusStr = choiceStatus->GetLabelText();
    }
    return statusStr;
}

wxString mmFilterTransactionsDialog::userTypeStr()
{
    wxString transCode = wxEmptyString;
    if (typeCheckBox->IsChecked())
    {
        if (cbTypeWithdrawal_->GetValue())
            transCode = TRANS_TYPE_WITHDRAWAL_STR;
        if (cbTypeDeposit_->GetValue())
            transCode << (transCode.IsEmpty() ? ("") : (", ")) << TRANS_TYPE_DEPOSIT_STR;
        if (cbTypeTransfer_->GetValue())
            transCode << (transCode.IsEmpty() ? ("") : (", ")) << TRANS_TYPE_TRANSFER_STR;
    }
    return transCode;
}

wxString mmFilterTransactionsDialog::userAmountRangeStr()
{
    wxString amountRangeStr;
    if (amountRangeCheckBox->IsChecked())
    {
        wxString minamt = amountMinEdit->GetValue();
        wxString maxamt = amountMaxEdit->GetValue();
        amountRangeStr = wxString::Format(_("Min: %s  Max: %s" ), minamt, maxamt);
    }
    return amountRangeStr;
}

wxString mmFilterTransactionsDialog::userTransNumberStr()
{
    wxString numberStr;
    if (transNumberCheckBox->IsChecked())
    {
        numberStr = transNumberEdit->GetValue().Trim().Lower();
    }
    return numberStr;
}

wxString mmFilterTransactionsDialog::userNotesStr()
{
    wxString notesStr;
    if (notesCheckBox->IsChecked())
    {
        notesStr = notesEdit->GetValue().Trim().Lower();
    }
    return notesStr;
}
